#! /bin/bash


pushd "$(dirname $BASH_SOURCE)" > /dev/null
if [ "$( uname )" = "Darwin" ] ; then ./mac-setup > /tmp/openjmlsetup 2>&1 ; fi
ROOT="$( pwd )"
popd > /dev/null
OPENJML_ROOT="$ROOT" "$ROOT/jdk/bin/javac" "$@"
