#! /bin/bash

cd $(dirname "$BASH_SOURCE[0]" )
BIN=../../../OpenJML21
if [ -z "$OJA" ]; then OJA=$BIN/openjml ; fi

rm -rf actual
$OJA --warn=list >> actual 2>&1
$OJA --warn=missing-specs --warn=list  >> actual 2>&1
$OJA --warn=missing-specs --warn= --warn=list  >> actual 2>&1
$OJA --warn=missing-specs --warn=reset --warn=list >> actual 2>&1
$OJA --warn=all --warn=list    >> actual 2>&1
$OJA --warn=none --warn=list   >> actual 2>&1
$OJA --no-warn=all --warn=list >> actual 2>&1

diff actual expected && rm -rf actual
