name: 'OpenJML Checkout'
description: 'A composite action that checks out the OpenJML repos for build and testing'
inputs:
  branch:
    description: 'The branch of OpenJML and Specs to checkout'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout OpenJML repos
      shell: bash
      run: |
        pwd
        ls
        git config --global core.autocrlf input
        git clone -b ${{ inputs.branch }} --depth 1 https://github.com/OpenJML/OpenJML
        pwd
        ls
        git clone -b ${{ inputs.branch }} --depth 1 https://github.com/OpenJML/Specs
        git clone -b master-21 --depth 1 https://github.com/OpenJML/OpenJMLDemo
        git clone -b master --depth 1 https://github.com/OpenJML/Solvers
        git clone -b master --depth 1 https://github.com/OpenJML/JMLAnnotations
        git clone -b master --depth 1 https://github.com/OpenJML/openjml.github.io
        pwd
        ls
