#!/bin/bash

## This script builds releases

umask 022
## DO not know why this is necessary.  ROOT, ANNOTATIONS, and
## SPECS are set from Eclipse project locations, but under
## Windows/Cygwin, the cp commands below fail with those settings.
## So we reset them here to the most common relative paths
## for those env. variables.  (FIXME)
if [[ "${COMSPEC}" != "" ]]; then
if [[ "${COKENV}" == "" ]]; then
	ROOT=..
	if [[ -e ../JMLAnnotations ]]; then
		ANNOTATIONS=../JMLAnnotations
	fi
	if [[ -e ../Specs ]]; then
		SPECS=../Specs
	fi
fi
fi

VERSION=`date +%Y%m%d`
NAME=openjml-${VERSION}.tar.gz

###### Build jmlspecs.jar openjml.jar:
	echo Building ${NAME} in `pwd`
	test -d temp && chmod -R u+rwx,a+rx temp || rm -rf temp
	test -d temp2 && chmod -R u+rwx,a+rx temp2 || rm -rf temp2
	(cd src/com/sun/tools/javac/resources; cat version.template | sed s/VERSION/OpenJML-${VERSION}/ > version.properties )
	cp src/com/sun/tools/javac/resources/version.properties bin/com/sun/tools/javac/resources/version.properties
	echo "openjml OpenJML-${VERSION}" > releaseTests/testJmlVersion/expected
	mkdir -p temp; chmod -R u+rwx,go+rx temp
	mkdir -p jars; chmod -R u+rwx,go+rx jars
	rm -f jars/jmlspecs.jar jars/openjml.jar
	echo "   " Copying files
	(cd temp; for j in ../otherlibs/* ; do jar xf $j; done; rm -rf META-INF )
	chmod -R a+rwx,go+rx ${ROOT}/OpenJDK/bin ${ROOT}/OpenJML/bin*
	cp -r ${ROOT}/OpenJDK/bin/* temp
	cp -r ${ROOT}/OpenJML/bin/* temp
	cp -r ${ROOT}/OpenJML/bin-runtime/* temp
	cp -r ${ANNOTATIONS}/bin/* temp
	mkdir -p temp/specs14 temp/specs15 temp/specs16; chmod -R u+rwx,a+rx temp
	cp -r ${SPECS}/java4/* temp/specs14
	find temp/specs14 -name .svn -exec rm -rf \{\} +
	cp -r temp/specs14/* temp/specs15
	cp -r ${SPECS}/java5/* temp/specs15
	find temp/specs15 -name .svn -exec rm -rf \{\} +
	cp -r temp/specs15/* temp/specs16
	cp -r ${SPECS}/java6/* temp/specs16
	find temp/specs16 -name .svn -exec rm -rf \{\} +
	echo "   " Creating jmlspecs.jar
	(cd temp/specs16; jar -cf ../../jars/jmlspecs.jar . )
	mkdir -p temp2; chmod -R u+rwx,a+rx temp2
	echo "   " Creating openjml.jar
	echo "Manifest-Version: 1.0" > temp2/manifest
	echo "Main-Class: org.jmlspecs.openjml.Main" >> temp2/manifest
	(cd temp; jar -cfm ../jars/openjml.jar ../temp2/manifest . )
	##cp jars/openjml.jar ../OpenJMLUI
	echo "   " jmlspecs.jar openjml.jar created

##### Build jmlruntime.jar
	mkdir -p temp2; chmod -R u+rwx,a+rx temp2
	mkdir -p jars; chmod -R u+rwx,a+rx jars
	rm -f jars/jmlruntime.jar
	cp -r bin-runtime/* temp2
	cp -r ${ANNOTATIONS}/bin/* temp2
	(cd temp2; jar -cf ../jars/jmlruntime.jar . ) 
	cp jars/jmlruntime.jar ${SPECS}
	rm -rf temp2
	echo "   " jmlruntime.jar created

##### Build the tar file
	cp openjml-system.properties jars
	cp openjml-template.properties jars
	(cd jars; \
	cp ../README . ; \
	tar -zcf ../${NAME} README openjml.jar jmlruntime.jar jmlspecs.jar *.properties )
	##rm -rf jars  ## We don't delete them because some tests use them
	echo "   " tar created

##### Some consistency checks
	if [[ -d ../OpenJML-DevUI ]]; then 
	    if [[ -d ../OpenJMLUI ]]; then 
		echo "   " Comparing icons and plugins ;
		diff ../OpenJMLUI/plugin.xml ../OpenJML-DevUI/plugin.xml || echo "PLUGINS ARE DIFFERENT - RESOLVE!!!!!" ;
		diff -r -x ".svn" ../OpenJMLUI/icons ../OpenJML-DevUI/icons || echo "ICON DIRECTORIES ARE DIFFERENT - RESOLVE!!!!!" ;
		diff -r -x ".svn" ../OpenJMLUI/html ../OpenJML-DevUI/html || echo "HTML DIRECTORIES ARE DIFFERENT - RESOLVE!!!!!" ;
	    else echo "   " "No ../OpenJMLUI to compare" ;
	    fi
	##else 
	    ##echo "   " "No ../OpenJML-DevUI to compare" ;
	fi
	echo "   " Checked icons and plugins

##### Copy stuff to the ui
	(cd ../OpenJMLUI; chmod -R u+rwx runtime openjml specs;
	 rm -rf runtime openjml specs ; )
	(cd ../OpenJMLUI; mkdir -p specs; chmod -R u+rwx,a+rx specs;)
	cp -rf ${SPECS}/java7 ../OpenJMLUI/specs
	cp -rf ${SPECS}/java6 ../OpenJMLUI/specs
	cp -rf ${SPECS}/java5 ../OpenJMLUI/specs
	cp -rf ${SPECS}/java4 ../OpenJMLUI/specs
	find ../OpenJMLUI/specs -name .svn -exec rm -rf \{\} +
	mkdir -p ../OpenJMLUI/openjml; chmod -R u+rwx,a+rx ../OpenJMLUI/openjml
	mkdir -p ../OpenJMLUI/runtime; chmod -R u+rwx,a+rx ../OpenJMLUI/runtime
	cp -r ${ROOT}/OpenJDK/bin/* ../OpenJMLUI/openjml
	cp -r ${ROOT}/OpenJML/bin/* ../OpenJMLUI/openjml
	cp -r ${ROOT}/OpenJML/bin-runtime/* ../OpenJMLUI/runtime
	chmod -R u+rwx,a+rx ${ANNOTATIONS}/bin/*
	cp -r ${ANNOTATIONS}/bin/* ../OpenJMLUI/runtime
	echo "   " "Copy to OpenJMLUI complete"


##### End	
	echo Release complete
