#! /bin/bash

DIR=C:/home/projects/OpenJML/trunk/OpenJML
SPC=-specs

JR=$DIR/openjml.jar
RT=$DIR/jmlruntime.jar

## FIXME - test whether the specs files actually work

## Use default specs - FIXME this does not work
#SPC=
#SP=

## Use internal specs 
#SP=$DIR/openjml.jar

## Use explicit specs file
SP=$DIR/jmlspecs.jar

## Use project specs files
SPECSDIR=C:/home/projects/Specs/trunk
#SP="${SPECSDIR}/java6;${SPECSDIR}/java5;${SPECSDIR}/java4"

java -jar "$JR" -classpath "$RT;$CLASSPATH" "$SPC" "$SP" $@
