bin.includes = feature.xml
topLevelElementType=feature
topLevelElementId=org.openjml.OpenJMLFeature
archivePrefix=tempBuild
skipBase=true
skipMaps=true
skipFetch=true
buildLabel=build
buildId=37
src.includes = feature.xml,\
               build.properties,\
               README,\
               .project
