#! /usr/bin/env bash

LOCAL=$(dirname "$BASH_SOURCE[0]" )
. "$LOCAL/../setup-script"

rm -rf MainApp.class actual
openjml-compile MainApp.java > actual || exit 1
openjml-run MainApp >> actual
diff actual expected && rm -rf actual
exit $?
