#!/bin/bash

## FIXME: This script works when run standalone in Cygwin or from Eclipse
## launched from Cygwin, but NOT from Eclipse launched from Windows.

## This script builds releases
## It is meant to be built from the root of the collection of OpenJML projects,
## that is, the current working directory should have OpenJML, Specs, JMLAnnotations,
## OpenJDK, and OpenJMLUI as direct subdirectories.


umask 022

## If these variables are not set, we set them to what they will be in 
## a standard Eclipse project setup for OpenJML.

if [[ "${ROOT}" == "" ]]; then
    ROOT=..
fi
if [[ "${ANNOTATIONS}" == "" ]]; then
    ANNOTATIONS=../JMLAnnotations
fi
if [[ "${SPECS}" == "" ]]; then
    SPECS=../Specs
fi

## Within Eclipse (in Cygwin at least), the paths that are defined do not work
## here, so we just set them.
    ROOT=..
    ANNOTATIONS=../JMLAnnotations
    SPECS=../Specs



VERSION=`date +%Y%m%d`
NAME=openjml-${VERSION}.tar.gz

	echo Building ${NAME} in `pwd`

##### Build jmlruntime.jar
	mkdir -p temp2; chmod -R u+rwx,a+rx temp2
	mkdir -p jars; chmod -R u+rwx,a+rx jars
	rm -f jars/jmlruntime.jar
	cp -r bin-runtime/* temp2
	cp -r ${ANNOTATIONS}/bin/* temp2
	(cd temp2; jar -cf ../jars/jmlruntime.jar . ) 
	cp jars/jmlruntime.jar ${SPECS}
	rm -rf temp2
	echo "   " jmlruntime.jar created

###### Build jmlspecs.jar openjml.jar:
	test -d temp && chmod -R u+rwx,a+rx temp || rm -rf temp
	test -d temp2 && chmod -R u+rwx,a+rx temp2 || rm -rf temp2
	(cd src/com/sun/tools/javac/resources; cat version.template | sed s/VERSION/OpenJML-${VERSION}/ > version.properties )
	cp src/com/sun/tools/javac/resources/version.properties bin/com/sun/tools/javac/resources/version.properties
	echo "openjml OpenJML-${VERSION}" > releaseTests/testJmlVersion/expected
	mkdir -p temp; chmod -R u+rwx,go+rx temp
	mkdir -p jars; chmod -R u+rwx,go+rx jars
	rm -f jars/jmlspecs.jar jars/openjml.jar
	echo "   " Copying files
	(cd temp; for j in ../otherlibs/* ; do jar xf $j; done; rm -rf META-INF )
	chmod -R a+rwx,go+rx ${ROOT}/OpenJDK/bin ${ROOT}/OpenJML/bin*
	cp -r ${ROOT}/OpenJDK/bin/* temp
	cp -r ${ROOT}/OpenJML/bin/* temp
	cp -r ${ROOT}/OpenJML/bin-runtime/* temp
	cp -r ${ANNOTATIONS}/bin/* temp
	mkdir -p temp/specs14 temp/specs15 temp/specs16 temp/specs17; chmod -R u+rwx,a+rx temp
	cp -r ${SPECS}/java4/* temp/specs14
    ( cd temp; find specs14 -name '.svn' -exec rm -rf {} + )
	cp -r temp/specs14/* temp/specs15
	cp -r ${SPECS}/java5/* temp/specs15
    ( cd temp; find specs15 -name '.svn' -exec rm -rf {} + )
    cp -r temp/specs15/* temp/specs16
    cp -r ${SPECS}/java6/* temp/specs16
    ( cd temp; find specs16 -name '.svn' -exec rm -rf {} + )
    cp -r temp/specs16/* temp/specs17
    cp -r ${SPECS}/java7/* temp/specs17
    ( cd temp; find specs17 -name '.svn' -exec rm -rf {} + )
	echo "   " Creating jmlspecs.jar
	(cd temp/specs17; jar -cf ../../jars/jmlspecs.jar . )
	mkdir -p temp2; chmod -R u+rwx,a+rx temp2
	echo "   " Creating openjml.jar
	echo "Manifest-Version: 1.0" > temp2/manifest
	echo "Main-Class: org.jmlspecs.openjml.Main" >> temp2/manifest
	(cd temp; jar -cfm ../jars/openjml.jar ../temp2/manifest . )
	##cp jars/openjml.jar ../OpenJMLUI
	echo "   " jmlspecs.jar openjml.jar created

##### Build the tar file
	cp openjml-system.properties jars
	cp openjml-template.properties jars
	(cd jars; \
	cp ../README . ; \
	tar -zcf ../${NAME} README openjml.jar jmlruntime.jar jmlspecs.jar *.properties )
	##rm -rf jars  ## We don't delete them because some tests use them
	echo "   " tar created

##### End	
	echo Release complete
