#! /bin/bash

DIR=C:/home/projects/OpenJML
JR=$DIR/jmlcheck.jar
RT=$DIR/jmlruntime.jar
##SP=$DIR/jmlspecs.jar

SD=$DIR/../JMLspecs/trunk
SP="$SD/java6;$SD/java5;$SD/java4"

java -jar "$JR" -classpath "$RT;$CLASSPATH" -specs "$SP" $@
