#! /bin/bash

DIR=C:/home/projects/OpenJML
JR=$DIR/jmlcheck.jar
RT=$DIR/jmlruntime.jar
##SP=$DIR/jmlspecs.jar

SD=$DIR/specs
SP="$SD/specs16;$SD/specs15;$SD/specs14"

java -jar "$JR" -classpath "$RT;$CLASSPATH" -specs "$SP" $@
