output.. = bin/
bin.includes = plugin.xml,\
               META-INF/,\
               icons/,\
               html/,\
               bin/,\
               syntaxes/,\
               OSGI-INF/l10n/bundle.properties
src.includes = src/,\
               icons/,\
               html/,\
               bin/,\
               syntaxes/,\
               TODO
jars.compile.order = .
