#! /usr/bin/env bash

## Might have trouble with symbolic links
cd $(dirname "${BASH_SOURCE[0]}")

. ../../setup-coverage json
mkdir -p ../../cov

ERR=0
DIRS=$@
if [ ${#DIRS} == 0 ] ; then DIRS=* ; fi

for d in $DIRS ; do 
  if [ -d $d ]; then
    echo DIR $d
    for j in $d/*.java; do
      if [ "$d" == "error" ]; then
        openjml -jmltesting --command=parse --show=json $j > /dev/null
      else
        openjml -jmltesting --command=parse --show=json $j
      fi
      ( diff $j.json $j.json.expected && rm $j.json ) || ERR=1
    done
  fi
done

if [ $ERR == 1 ] ; then echo JSON TESTS FAILED; fi
exit $ERR
