#! /bin/bash

newfailures=`grep FAILED log-* | sed -e 's/.*testsuites[.]//' | comm -13 known-failures -`
newsuccesses=`grep FAILED log-* | sed -e 's/.*testsuites[.]//' | comm -23 known-failures -`
echo Unexpected successes
echo $newsuccesses
echo Unexpected failures
echo $newfailures
if [ "$1" == "-print" ]; then exit 0 ; fi
for t in $newfailures ; do
    echo Retrying $t
    ./runtests $t
done

