#! /bin/bash

newfailures=`grep FAILED log-* | sed -e 's/.*testsuites[.]//' | comm -13 known-failures -`
newsuccesses=`grep FAILED log-* | sed -e 's/.*testsuites[.]//' | comm -23 known-failures -`
echo Unexpected successes
echo $newsuccesses
echo Unexpected failures
echo $newfailures
if [ "$1" == "-print" ]; then exit 0 ; fi
ERR=0
for t in $newfailures ; do
    echo Retrying $t
    ./runtests $t || ERR=1
done
echo Completed retry $ERR
exit $ERR
