#! /bin/bash

## This script is intended for internal use.

## Arguments ./run-summary <name of log file> <names of testcases>
## This script runs all the tests in the given testcase, counting successes, failures and skipped tests
## More than one testcase may be listed, with all the results combined into the one log file.

## The first argument is (usually) the name of the log-file
if [ $# -eq 0 ]; then
    echo "error: run-summary <path-to-log-file> <testcase names>"
    exit 1
elif [ $# -eq 1 ]; then
    f=log-$1
    #echo Using $f as the log file for testcase $1
else
    f=$1; shift
fi

# The rest of the arguments are testcase names to be run sequentially,
# with output captured in the log file and a single summary line after all cases are complete

while true; do
r=`./runtests $* 2>&1 | tee $f | grep failures`
if [ -n "$r" ]; then break; fi
echo Retrying summary for $@
done

actfailures=`echo $r | sed -e 's/^.*timeouts,//' | sed -e 's/failures,.*$//' | tr -d ' ' `

if [ "$actfailures" != "0" ]; then m="<<<<<<<<<<<< $actfailures failures" ; else m="" ; fi
echo -e "$f\t" $r $m
