#! /bin/bash

n=`ps -ef | grep runtests | wc -l`
if [ $n != "1" ]; then
  echo "tests already running"
  ps -ef | grep runtests | grep -v grep
  exit 1
fi

cd $(dirname "$BASH_SOURCE")

./run-summary log-racmost           "101/0"	racArithmeticModes racdemoexamples racfeatures racJML racnew3 racnewLoops racnewWithSpecs racsystem &
./run-summary log-racfiles     	"20/46" racfiles  &
./run-summary log-racnew       	"128/15" racnew  &
./run-summary log-racnew2      	"73/2"	racnew2 &
./run-summary log-racreadable	"0/2"	racreadable & 

./run-summary log-access+  	"151/4" access arith assignable compilationUnit compiler deprecation  &
./run-summary log-binaries 	"5/1"	binaries  &
./run-summary log-bugs     	"23/0"	bugs  &
./run-summary log-esc1     	"91/0"  esc1  &
./run-summary log-esc2     	"109/0" esc2  &
#./run-summary log-escarith+ 	"56/17" escArithmeticModes escArithmeticModes2  &
./run-summary log-escbv     	"12/0"  escbitvector  &
./run-summary log-escConst+ 	"68/0"  escConstantFields escCounterexamples escaccessible esccode escconstructor  &
./run-summary log-escall+   	"85/0"  escall2 escall3   &
./run-summary log-esccallable	"31/1"  esccallable   &
sleep 300
./run-summary log-escfunc+	"28/0"  escfunction escgeneric  &
./run-summary log-escinclau+	"104/0" escinclause escinline esclocation escnewBoxing escnewassignable escnowarn escoption escprimitivetypes escreadable escstrings  &
./run-summary log-escnew+   	"158/1" escnew escnew2 escvisibility escvisibility1  &
./run-summary log-escnew3   	"63/1"  escnew3 &
./run-summary log-esclambdas   	"25/3"  esclambdas  &
./run-summary log-escm         	"13/0"  escm   &
./run-summary log-expr+        	"64/0"  expressions escJML flow  &
./run-summary log-generics     	"13/2"  generics   &
./run-summary log-harness	"0/5"	harnesstests &
./run-summary log-inter+       	"159/0"	internalSpecs jmltypes lblexpression methodspecs modelghost namelookup notspecified nowarn positions prettyprinting purity  &
sleep 300
./run-summary log-matchClass	"49/3"  matchClasses  &
./run-summary log-modifiers    	"192/0" modifiers  &
./run-summary log-redundant+   	"108/1"	escenums redundant statements strict sysclasses typecheckingJmlTypes typecheckingvisibility &
./run-summary log-scanner      	"80/3"	scanner  &
./run-summary log-typecheck	"181/0"	typechecking &
./run-summary log-typeclause	"123/0"	typeclauses  &
./run-summary log-SpecsBase    	"???"	SpecsBase  &
./run-summary log-SpecsEsc     	"3/0"	SpecsEsc  &


n=`ps -ef | grep runtests | wc -l`
while [ $n != "1" ]; do
  ##echo still running:
  ##ps -ef | grep runtests
  sleep 60
  n=`ps -ef | grep runtests | wc -l`
done
echo Completed
