#! /bin/bash
shopt -s expand_aliases

n=`ps -ef | grep runtests | wc -l`
if [ $n != "1" ]; then
  echo "tests already running"
  ps -ef | grep runtests | grep -v grep
  exit 1
fi

cd $(dirname "$BASH_SOURCE")

alias lsc="ps au | grep summary | grep -v grep | awk '{ print \$13 }' | sort -u | wc -l"
alias lst="ps au | grep summary | grep -v grep | awk '{ print \$13 }' | sort -u"
##alias wt="while [ \$(lsc) -gt 5 ]; do echo Waiting \$(lsc); sleep 30; done; echo proceeding \$(lsc)" 
alias wt="while [ \$(lsc) -gt 5 ]; do sleep 30; done" 

## The sleeps are inserted so we don't try to run all of the tasks at once

./run-summary log-racmost       "101/0"	racArithmeticModes racdemoexamples racfeatures racJML racnew3 racnewLoops racnewWithSpecs racsystem &
./run-summary log-racfiles     	"26/41" racfiles  &
./run-summary log-racnew       	"127/14" racnew  &
./run-summary log-racnew2      	"69/0"	racnew2 &
./run-summary log-racreadable	"2/0"	racreadable & 

./run-summary log-access+  	"155/0" access arith assignable compilationUnit compiler deprecation  &
wt
./run-summary log-binaries 	"5/1"	binaries  &
./run-summary log-bugs     	"23/0"	bugs  &
./run-summary log-esc1     	"93/0"  esc1  &
wt
./run-summary log-esc2     	"109/0" esc2  &
#./run-summary log-escarith+ 	"56/17" escArithmeticModes escArithmeticModes2  &
./run-summary log-escbv     	"12/0"  escbitvector  &
./run-summary log-escConst+ 	"68/0"  escConstantFields escCounterexamples escaccessible esccode escconstructor  &
wt
./run-summary log-escall2   	"30/0"  escall2   &
./run-summary log-escall3   	"55/0"  escall3   &
./run-summary log-esccallable	"29/0"  esccallable   &
wt
./run-summary log-escfunc+	"28/0"  escfunction escgeneric  &
./run-summary log-escinclau+	"91/0" escinclause escinline esclocation escnewBoxing escnewassignable escoption escprimitivetypes escreadable escstrings  &
./run-summary log-escvis  	"59/0"  escvisibility escvisibility1  &
wt
./run-summary log-escnew   	"64/1"  escnew &
./run-summary log-escnew2   	"35/0"  escnew2 &
./run-summary log-escnew3   	"63/1"  escnew3 &
wt
./run-summary log-esclambdas   	"25/3"  esclambdas  &
./run-summary log-escm         	"13/0"  escm   &
./run-summary log-expr+        	"64/0"  expressions escJML flow  &
wt
./run-summary log-generics     	"14/1"  generics   &
./run-summary log-harness	"5/0"	harnesstests &
./run-summary log-inter+       	"140/0"	internalSpecs jmltypes lblexpression methodspecs modelghost namelookup positions prettyprinting purity  &
wt
./run-summary log-matchClass	"52/0"  matchClasses  &
./run-summary log-modifiers    	"191/0" modifiers  &
./run-summary log-redundant+   	"105/1"	escenums redundant statements strict sysclasses typecheckingJmlTypes typecheckingvisibility &
./run-summary log-scanner      	"91/0"	scanner  &
wt
./run-summary log-typecheck	"207/0"	typechecking &
./run-summary log-typeclause	"123/0"	typeclauses  &
./run-summary log-SpecsBase    	"283/5"	SpecsBase  &
./run-summary log-SpecsEsc     	"3/0"	SpecsEsc  &


while [ $(lsc) -gt "0" ]; do
  ##echo still running: `lst`
  sleep 30
done
echo Completed
