#! /bin/bash

## This script runs the JUnit tests (directly, without using Eclipse)
## It does so by running the OpenJMLTestRunner.java program, which is an OpenJML_specific
## JUnit-test runner, after compiling all the
## unit test drivers in OpenJMLTest/src/org/jmlspecs/openjmltest/testcases/

## If the environmental variable COV is set, then coverage measurements are reported, and
## are stored in the one coverage data file 'unit-$1' where $1 is the name of the first testsuite listed in the command-line

## $R is the location of the directory containing this script, with
## $R/.. expected to be OpenJMLTest, which should be a sibling of OpenJML21

trap ctrl_c INT

function ctrl_c() {
    rm -f the.jml.lock unittestframework
    echo Aborted
    exit 1
}

F=$(realpath "BASH_SOURCE")
R=$(dirname "$F")
export ROOT="$R/../../OpenJML21"
TEST="$R/../../OpenJMLTest"
JROOT=$R/../libs
JUNIT="$JROOT/junit-4.13.2.jar:$JROOT/hamcrest-core-1.3.jar:$JROOT/junit-jupiter-api-5.5.2.jar:$JROOT/apiguardian-api-1.1.0.jar:$JROOT/opentest4j-1.3.0.jar"
export NJAVAC=`echo "$ROOT"/build/*/jdk/bin/javac`
NJAVA=`echo "$ROOT"/build/*/jdk/bin/java`

. "$TEST/setup-coverage" unit-$1

. "$ROOT/setup-exports"

cd "$R"
rm -f *.class
CL=`echo "$ROOT"/build/*/jdk/modules/*  | grep -v META | sed -e "s/ /:/g"`
export CP=".:../src:$JUNIT:$CL"

while true; do
  if make -q unittestframework ; then break; fi  ## make is up to date so go on to execute the compiled program

  if ! (( set -o noclobber; echo x > the.jml.lock ) &> /dev/null ) ; then echo "Waiting for the.jml.lock" ; sleep 3; continue; fi ## Check until the temp file does not exist

  ## Have the lock and last I checked the make was not up to date, so do the compile

  ## Use make instead of the explicit compile to use make's up-to-date-ness checking
  ## Make needs NJAVAC CP EXPORTS ROOT (hence these are exported)
  echo Compiling for $@
  make unittestframework

  rm -f the.jml.lock ## Release the lock
  if [ ! -e OpenJMLTestRunner.class ]; then echo Missing OpenJMLTestRunner.class $@; continue; fi ## Unexpectedly missing the compile result, so try all over again 

  echo Compilation complete
  break
done

## Now run the compiled Test program -- stdout and stderr output are combined into one output
## This almost duplicates running openjml-java in the development environment, except for the addition of AGENT and the specific classpath
## echo Running $@
( cd ..; "$ROOT"/openjml-java $AGENT  -cp "unittests:src:$JUNIT" $EXPORTS OpenJMLTestRunner "$@" 2>&1 )
#( cd ..; OPENJML_INSTALL="$ROOT" OPENJML_SOLVERS="$ROOT/../../Solvers" OPENJML_SPECS="$ROOT/../../Specs" "$NJAVA" $AGENT -cp "unittests:src:$JUNIT" $EXPORTS OpenJMLTestRunner "$@" 2>&1 )
