#! /bin/bash

## This script runs the JUnit tests (directly, without using Eclipse)
## It does so by running the Test.java program, after compiling all the
## unit test drivers in OpenJMLTest/src/org/jmlspecs/openjmltest/testcases/

## $R is the location of the directory containing this script, with
## $R/.. expected to be OpenJMLTest, which should be a sibling of OpenJML21

R=$( cd $(dirname "$BASH_SOURCE") && pwd)
ROOT=$R/../../OpenJML21
JROOT=$R/../libs
JUNIT="$JROOT/junit-4.13.2.jar:$JROOT/hamcrest-core-1.3.jar:$JROOT/junit-jupiter-api-5.5.2.jar:$JROOT/apiguardian-api-1.1.0.jar"
NJAVAC=$ROOT/build/*/jdk/bin/javac
NJAVA=$ROOT/build/*/jdk/bin/java


cd $R
rm -f *.class
CL=`echo $ROOT/build/*/jdk/modules/*  | grep -v META | sed -e "s/ /:/g"`
CP=".:../src:$JUNIT:$CL"

OPTIONS="-Xlint:unchecked -Xdiags:verbose"

EXPORTS="--add-modules jdk.compiler,java.base --add-exports=jdk.compiler/org.jmlspecs.openjml=ALL-UNNAMED  --add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-exports=jdk.compiler/org.jmlspecs.openjml=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports=jdk.compiler/org.jmlspecs.openjml.proverinterface=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED --add-exports=jdk.compiler/org.jmlspecs.openjml.visitors=ALL-UNNAMED"

while ! NOJML= $NJAVAC $OPTIONS -cp $CP -p /Users/davidcok/projects/OpenJML21/OpenJML/OpenJML21/build/macosx-x86_64-server-release/jdk/modules $EXPORTS Test.java ../src/org/jmlspecs/openjmltest/testcases/*.java ; do

   # Build can fail because of race conditions between compiles if so then multiple runtests are started at once
   echo Build failed for $@
   sleep 10
done

## Now run the compiled Test progam
( cd ..; OPENJML_ROOT="$ROOT/../../Solvers" $NJAVA -javaagent:$HOME/mylib/jacoco/lib/jacocoagent.jar -cp unittests:src:$JUNIT $EXPORTS Test $@ 2>&1 )
