#! /bin/bash


JDK=/Users/davidcok/projects/jdkC/jdk
OPENJML=/Users/davidcok/projects/OpenJML-Vendor/OpenJML/OpenJDKModule

cp -R $JDK/[a-zA-Z]* $OPENJML
cp $JDK/.gitignore $OPENJML

diff -r $JDK $OPENJML
