#! /bin/bash

R1=$(realpath "$BASH_SOURCE" ) ## realpath needed to resolve symlinks; R1 will be the path to this file
cd $(dirname "$R1") # path containing this file, namely OpenJDKModule

cp -p /Users/davidcok/cok/texstuff/papers/JMLBook/OpenJMLUserGuide.pdf release-files
cp -p /Users/davidcok/cok/texstuff/papers/JMLBook/OpenJMLUserGuide.pdf ../../openjml.github.io/documentation
latest=`ls -t ~/Desktop/JML_Reference_Manual*.pdf | head -1`
echo Latest Refman $latest
cp -p $latest release-files
cp -p $latest ../../openjml.github.io/documentation

ls -lat release-files/*.pdf

echo Update tutorial files
make tutorial
