#! /usr/bin/env bash

FILE="$BASH_SOURCE[0]"
DIR=`dirname "$FILE"`
cd "$DIR"

(\
rm -f *.class ;\
openjml --rac T.java ;\
openjml -Xprefer:source --compile P.java ;\
openjml-java T ;\
) >& actual
diff actual RUN.out && rm -rf actual

(\
rm -f *.class ;\
openjml --rac T.java P.java ;\
openjml-java T ;\
) >& actual2
diff actual2 RUN2.out && rm -rf actual2
