#! /bin/bash

export TESTNAME=$1
export TESTLOC=../releaseTests
export CMD=$2

echo TESTING ${TESTNAME}
${CMD} | grep -v "Note: " | tr -d '\r' > ${TESTLOC}/${TESTNAME}/actual
RES=1
diff ${TESTLOC}/${TESTNAME}/actual ${TESTLOC}/${TESTNAME}/expected && echo ${TESTNAME} OK && RES=0 && rm -f ${TESTLOC}/${TESTNAME}/actual

exit $RES