#! /bin/bash

cd $(dirname $BASH_SOURCE[0] )  
BIN=../../../OpenJML21
if [ -z "$OJA" ]; then OJA=$BIN/openjml; fi

rm -rf Run.class actual
$BIN/openjml-compile Run.java > actual || exit 1
echo COMPILED >> actual
$BIN/openjml-run Run >> actual
LOC=`(cd ../../../..; pwd)`
sed -e "s%\$ROOT%$LOC%g" < expected | ( diff - actual && rm -rf actual )
exit $?
