#! /usr/bin/env bash

LOCAL=$(dirname "$BASH_SOURCE[0]" )
. "$LOCAL/../setup-script"

(\
echo Test 1 ;\
openjml --check D.java ; \
echo EXIT $? ;\
echo Test 2; \
openjml --check D.java ;\
echo EXIT $? ;\
echo Test 3; \
openjml --check -nowarn D.java ;\
echo EXIT $? ;\
echo Test 4; \
openjml --check -Werror -nowarn D.java ; \
echo EXIT $? ;\
echo Test 5; \
openjml --check -Werror D.java ; \
echo EXIT $? ;\
) >& actual

(\
echo Test 1 ;\
openjml --check K.java ; \
echo EXIT $? ;\
echo Test 2; \
openjml --check K.java ;\
echo EXIT $? ;\
echo Test 3; \
openjml --check -nowarn K.java ;\
echo EXIT $? ;\
echo Test 4; \
openjml --check -Werror -nowarn K.java ; \
echo EXIT $? ;\
echo Test 4a; \
openjml --check -nowarn -Werror K.java ; \
echo EXIT $? ;\
echo Test 5; \
openjml --check -Werror K.java ; \
echo EXIT $? ;\
) >> actual 2>&1

## Test that -Xlint works
(\
echo Test -Xlint; \
openjml --check -Xlint:text-blocks t/TB.java ;\
echo Test -Xlint off ;\
openjml --check t/TB.java ;\
) >> actual 2>&1

diff actual expected && rm -rf actual
exit $?

