/**
 * Copyright (c) 2018, biezhi nice (hellokaton@gmail.com)
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.hellokaton.blade.validator;

import com.hellokaton.blade.kit.PatternKit;
import lombok.AccessLevel;
import lombok.NoArgsConstructor;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

import static java.lang.String.format;

/**
 * Validators
 * <p>
 * When you use the validator, the input parameters meet the meaning of the calling method and the validation passes,
 * otherwise a ValidatorException is throw.
 * <p>
 * By default, all prompts are returned based on I18N_MAP. The default language is English.
 * If you want a custom to throw a message, you can call the throwMessage method.
 *
 * @author biezhi
 * @date 2018/4/21
 */
@NoArgsConstructor(access = AccessLevel.PRIVATE)
public final class Validators {

    /*@ spec_public */ private static final Map<String, String> I18N_MAP = new HashMap<>();

    /*@ spec_public */ private static String i18nPrefix = "EN_";

    static {
        I18N_MAP.put("CN_NOT_NULL", "CN NO NULL");
        I18N_MAP.put("CN_NOT_EMPTY", "CN NO VACIO");
        I18N_MAP.put("CN_MORE_THAN", "CN MAS QUE %s");
        I18N_MAP.put("CN_LESS_THAN", "CN MENOS QUE %s");
        I18N_MAP.put("CN_CONTAINS", "CN CONTIENE %s");
        I18N_MAP.put("CN_LOWER_THAN", "CN MAS BAJO QUE %s");
        I18N_MAP.put("CN_GREATER_THAN", "CN MAYOR QUE %s");
        I18N_MAP.put("CN_IS_EMAIL", "CN ES EMAIL");
        I18N_MAP.put("CN_IS_URL", "CN ES URL");

        I18N_MAP.put("EN_NOT_NULL", "must not be null.");
        I18N_MAP.put("EN_NOT_EMPTY", "must not be empty.");
        I18N_MAP.put("EN_MORE_THAN", "must have more than %s chars.");
        I18N_MAP.put("EN_LESS_THAN", "must have less than %s chars.");
        I18N_MAP.put("EN_CONTAINS", "must contain %s");
        I18N_MAP.put("EN_LOWER_THAN", "must be lower than %s.");
        I18N_MAP.put("EN_GREATER_THAN", "must be greater than %s.");
        I18N_MAP.put("EN_IS_EMAIL", "must be a email.");
        I18N_MAP.put("EN_IS_URL", "must be a url.");
    }

    /*@
    @ public normal_behavior // Generated by Daikon
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP == \old(com.hellokaton.blade.validator.Validators.I18N_MAP);
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName() == \old(com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName());
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @*/
    public static void useChinese() {
        i18nPrefix = "CN_";
    }

    /*@
    @ public normal_behavior // Generated by Daikon
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP == \old(com.hellokaton.blade.validator.Validators.I18N_MAP);
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName() == \old(com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName());
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix == \old(com.hellokaton.blade.validator.Validators.i18nPrefix);
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals(\old(com.hellokaton.blade.validator.Validators.i18nPrefix.toString()));
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ ensures \result.getClass().getName() == com.hellokaton.blade.validator.SimpleValidation.class.getName();
    @*/
    /**
     * The input object is not null. if yes, the check passes
     *
     * @return Validation
     */
    public static <T> Validation<T> notNull() {
        return notNull(I18N_MAP.get(i18nPrefix + "NOT_NULL"));
    }

    /*@
    @ public normal_behavior // Generated by Daikon
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ requires msg != null;
    @ requires msg.toString().equals("\u4e0d\u5141\u8bb8\u4e3a NULL");
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP == \old(com.hellokaton.blade.validator.Validators.I18N_MAP);
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName() == \old(com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName());
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix == \old(com.hellokaton.blade.validator.Validators.i18nPrefix);
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals(\old(com.hellokaton.blade.validator.Validators.i18nPrefix.toString()));
    @ ensures msg.toString().equals(\old(msg.toString()));
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ ensures msg.toString().equals("\u4e0d\u5141\u8bb8\u4e3a NULL");
    @ ensures \result.getClass().getName() == com.hellokaton.blade.validator.SimpleValidation.class.getName();
    @*/
    /**
     * The input object is not null. if yes, the check passes
     *
     * @param msg error message after verification failed
     * @return Validation
     */
    public static <T> Validation<T> notNull(String msg) {
        return SimpleValidation.from(Objects::nonNull, msg);
    }

    /*@
    @ public normal_behavior // Generated by Daikon
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP == \old(com.hellokaton.blade.validator.Validators.I18N_MAP);
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName() == \old(com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName());
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix == \old(com.hellokaton.blade.validator.Validators.i18nPrefix);
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals(\old(com.hellokaton.blade.validator.Validators.i18nPrefix.toString()));
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ ensures \result != null;
    @ ensures \result.getClass().getName() == com.hellokaton.blade.validator.SimpleValidation.class.getName();
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName() != \result.getClass().getName();
    @*/
    /**
     * The input string is not empty. if yes, the check passes
     *
     * @return Validation
     */
    public static Validation<String> notEmpty() {
        return notEmpty(I18N_MAP.get(i18nPrefix + "NOT_EMPTY"));
    }

    /*@
    @ public normal_behavior // Generated by Daikon
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ requires msg != null;
    @ requires msg != null;
    @ requires msg.toString().equals("\u4e0d\u5141\u8bb8\u4e3a\u7a7a");
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix.toString().compareTo(msg.toString()) < 0;
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP == \old(com.hellokaton.blade.validator.Validators.I18N_MAP);
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName() == \old(com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName());
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix == \old(com.hellokaton.blade.validator.Validators.i18nPrefix);
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals(\old(com.hellokaton.blade.validator.Validators.i18nPrefix.toString()));
    @ ensures msg.toString().equals(\old(msg.toString()));
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ ensures msg.toString().equals("\u4e0d\u5141\u8bb8\u4e3a\u7a7a");
    @ ensures \result != null;
    @ ensures \result.getClass().getName() == com.hellokaton.blade.validator.SimpleValidation.class.getName();
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName() != \result.getClass().getName();
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().compareTo(msg.toString()) < 0;
    @*/
    /**
     * The input string is not empty. if yes, the check passes
     *
     * @param msg error message after verification failed
     * @return Validation
     */
    public static Validation<String> notEmpty(String msg) {
        return SimpleValidation.from(s -> null != s && !s.isEmpty(), msg);
    }

    /*@
    @ public normal_behavior // Generated by Daikon
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ requires size == 3 || size == 5;
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP == \old(com.hellokaton.blade.validator.Validators.I18N_MAP);
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName() == \old(com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName());
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix == \old(com.hellokaton.blade.validator.Validators.i18nPrefix);
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals(\old(com.hellokaton.blade.validator.Validators.i18nPrefix.toString()));
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @*/
    /**
     * The input string must be more than or equal to size. if yes, the check passes
     *
     * @param size string size
     * @return Validation
     */
    public static Validation<String> moreThan(int size) {
        return notEmpty().and(moreThan(size, I18N_MAP.get(i18nPrefix + "MORE_THAN")));
    }

    /*@
    @ public normal_behavior // Generated by Daikon
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ requires size == 3 || size == 5;
    @ requires msg != null;
    @ requires msg.toString().equals("\u5fc5\u987b\u5927\u4e8e\u7b49\u4e8e %s \u4e2a\u5b57\u7b26");
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP == \old(com.hellokaton.blade.validator.Validators.I18N_MAP);
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName() == \old(com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName());
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix == \old(com.hellokaton.blade.validator.Validators.i18nPrefix);
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals(\old(com.hellokaton.blade.validator.Validators.i18nPrefix.toString()));
    @ ensures msg.toString().equals(\old(msg.toString()));
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ ensures msg.toString().equals("\u5fc5\u987b\u5927\u4e8e\u7b49\u4e8e %s \u4e2a\u5b57\u7b26");
    @*/
    /**
     * The input string must be more than or equal to size. if yes, the check passes
     *
     * @param size string size
     * @param msg  error message after verification failed
     * @return Validation
     */
    public static Validation<String> moreThan(int size, String msg) {
        return notEmpty().and(SimpleValidation.from((s) -> s.length() >= size, format(msg, size)));
    }

    /*@
    @ public normal_behavior // Generated by Daikon
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ requires size == 20 || size == 100;
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP == \old(com.hellokaton.blade.validator.Validators.I18N_MAP);
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName() == \old(com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName());
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix == \old(com.hellokaton.blade.validator.Validators.i18nPrefix);
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals(\old(com.hellokaton.blade.validator.Validators.i18nPrefix.toString()));
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @*/
    /**
     * The input string must be less than or equal to size. if yes, the check passes
     *
     * @param size string size
     * @return Validation
     */
    public static Validation<String> lessThan(int size) {
        return lessThan(size, I18N_MAP.get(i18nPrefix + "LESS_THAN"));
    }

    /*@
    @ public normal_behavior // Generated by Daikon
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ requires size == 20 || size == 100;
    @ requires msg != null;
    @ requires msg.toString().equals("\u5fc5\u987b\u5c0f\u4e8e\u7b49\u4e8e %s \u4e2a\u5b57\u7b26");
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP == \old(com.hellokaton.blade.validator.Validators.I18N_MAP);
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName() == \old(com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName());
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix == \old(com.hellokaton.blade.validator.Validators.i18nPrefix);
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals(\old(com.hellokaton.blade.validator.Validators.i18nPrefix.toString()));
    @ ensures msg.toString().equals(\old(msg.toString()));
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ ensures msg.toString().equals("\u5fc5\u987b\u5c0f\u4e8e\u7b49\u4e8e %s \u4e2a\u5b57\u7b26");
    @*/
    /**
     * The input string must be less than or equal to size. if yes, the check passes
     *
     * @param size string size
     * @param msg  error message after verification failed
     * @return Validation
     */
    public static Validation<String> lessThan(int size, String msg) {
        return notEmpty().and(SimpleValidation.from((s) -> s.length() <= size, format(msg, size)));
    }

    /*@
    @ public normal_behavior // Generated by Daikon
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ requires minSize == 3 || minSize == 5;
    @ requires maxSize == 20 || maxSize == 100;
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP == \old(com.hellokaton.blade.validator.Validators.I18N_MAP);
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName() == \old(com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName());
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix == \old(com.hellokaton.blade.validator.Validators.i18nPrefix);
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals(\old(com.hellokaton.blade.validator.Validators.i18nPrefix.toString()));
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @*/
    /**
     * The length of the input string must be between minSize and maxSize. if yes, the check passes
     *
     * @param minSize string min size
     * @param maxSize string max size
     * @return Validation
     */
    public static Validation<String> length(int minSize, int maxSize) {
        return moreThan(minSize).and(lessThan(maxSize));
    }

    /*@
    @ public normal_behavior // Generated by Daikon
    @ requires true;
    @*/
    /**
     * The input parameter must contain the string c. if yes, the check passes
     *
     * @param c contained strings
     * @return Validation
     */
    public static Validation<String> contains(String c) {
        return contains(c, I18N_MAP.get(i18nPrefix + "CONTAINS"));
    }

    /*@
    @ public normal_behavior // Generated by Daikon
    @ requires true;
    @*/
    /**
     * The input parameter must contain the string c. if yes, the check passes
     *
     * @param c   contained strings
     * @param msg error message after verification failed
     * @return Validation
     */
    public static Validation<String> contains(String c, String msg) {
        return notEmpty().and(SimpleValidation.from((s) -> s.contains(c), format(msg, c)));
    }

    /*@
    @ public normal_behavior // Generated by Daikon
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ requires max == 5 || max == 20;
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP == \old(com.hellokaton.blade.validator.Validators.I18N_MAP);
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName() == \old(com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName());
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix == \old(com.hellokaton.blade.validator.Validators.i18nPrefix);
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals(\old(com.hellokaton.blade.validator.Validators.i18nPrefix.toString()));
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ ensures \result.getClass().getName() == com.hellokaton.blade.validator.SimpleValidation.class.getName();
    @*/
    /**
     * Determine if the input int parameter is lower than max. if yes, the check passes
     *
     * @param max input must be < max number
     * @return Validation
     */
    public static Validation<Integer> lowerThan(int max) {
        return lowerThan(max, I18N_MAP.get(i18nPrefix + "LOWER_THAN"));
    }

    /*@
    @ public normal_behavior // Generated by Daikon
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ requires max == 5 || max == 20;
    @ requires msg != null;
    @ requires msg.toString().equals("\u5fc5\u987b\u5c0f\u4e8e %s");
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP == \old(com.hellokaton.blade.validator.Validators.I18N_MAP);
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName() == \old(com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName());
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix == \old(com.hellokaton.blade.validator.Validators.i18nPrefix);
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals(\old(com.hellokaton.blade.validator.Validators.i18nPrefix.toString()));
    @ ensures msg.toString().equals(\old(msg.toString()));
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ ensures msg.toString().equals("\u5fc5\u987b\u5c0f\u4e8e %s");
    @ ensures \result.getClass().getName() == com.hellokaton.blade.validator.SimpleValidation.class.getName();
    @*/
    /**
     * Determine if the input int parameter is lower than max. if yes, the check passes
     *
     * @param max input must be < max number
     * @param msg error message after verification failed
     * @return Validation
     */
    public static Validation<Integer> lowerThan(int max, String msg) {
        return SimpleValidation.from((i) -> i < max, format(msg, max));
    }

    /*@
    @ public normal_behavior // Generated by Daikon
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ requires min == 3 || min == 10;
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP == \old(com.hellokaton.blade.validator.Validators.I18N_MAP);
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName() == \old(com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName());
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix == \old(com.hellokaton.blade.validator.Validators.i18nPrefix);
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals(\old(com.hellokaton.blade.validator.Validators.i18nPrefix.toString()));
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ ensures \result.getClass().getName() == com.hellokaton.blade.validator.SimpleValidation.class.getName();
    @*/
    /**
     * Determine if the input int parameter is greater than min. if yes, the check passes
     *
     * @param min input must be > min number
     * @return Validation
     */
    public static Validation<Integer> greaterThan(int min) {
        return greaterThan(min, I18N_MAP.get(i18nPrefix + "GREATER_THAN"));
    }

    /*@
    @ public normal_behavior // Generated by Daikon
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ requires min == 3 || min == 10;
    @ requires msg != null;
    @ requires msg.toString().equals("\u5fc5\u987b\u5927\u4e8e %s");
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP == \old(com.hellokaton.blade.validator.Validators.I18N_MAP);
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName() == \old(com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName());
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix == \old(com.hellokaton.blade.validator.Validators.i18nPrefix);
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals(\old(com.hellokaton.blade.validator.Validators.i18nPrefix.toString()));
    @ ensures msg.toString().equals(\old(msg.toString()));
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ ensures msg.toString().equals("\u5fc5\u987b\u5927\u4e8e %s");
    @ ensures \result.getClass().getName() == com.hellokaton.blade.validator.SimpleValidation.class.getName();
    @*/
    /**
     * Determine if the input int parameter is greater than min. if yes, the check passes
     *
     * @param min input must be > min number
     * @param msg error message after verification failed
     * @return Validation
     */
    public static Validation<Integer> greaterThan(int min, String msg) {
        return SimpleValidation.from((i) -> i > min, format(msg, min));
    }

    /*@
    @ public normal_behavior // Generated by Daikon
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ requires min == 3 || min == 10;
    @ requires max == 5 || max == 20;
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP == \old(com.hellokaton.blade.validator.Validators.I18N_MAP);
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName() == \old(com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName());
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix == \old(com.hellokaton.blade.validator.Validators.i18nPrefix);
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals(\old(com.hellokaton.blade.validator.Validators.i18nPrefix.toString()));
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @*/
    /**
     * Determine if the input int parameter is it in a range. if yes, the check passes
     *
     * @param min input must be > min number
     * @param max input must be < max number
     * @return Validation
     */
    public static Validation<Integer> range(int min, int max) {
        return greaterThan(min).and(lowerThan(max));
    }

    /*@
    @ public normal_behavior // Generated by Daikon
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP == \old(com.hellokaton.blade.validator.Validators.I18N_MAP);
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName() == \old(com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName());
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix == \old(com.hellokaton.blade.validator.Validators.i18nPrefix);
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals(\old(com.hellokaton.blade.validator.Validators.i18nPrefix.toString()));
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @*/
    /**
     * Determine if the input parameter is a Email. if yes, the check passes
     *
     * @return Validation
     */
    public static Validation<String> isEmail() {
        return isEmail(I18N_MAP.get(i18nPrefix + "IS_EMAIL"));
    }

    /*@
    @ public normal_behavior // Generated by Daikon
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ requires msg != null;
    @ requires msg.toString().equals("\u4e0d\u662f\u4e00\u4e2a\u5408\u6cd5\u7684\u90ae\u7bb1");
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP == \old(com.hellokaton.blade.validator.Validators.I18N_MAP);
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName() == \old(com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName());
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix == \old(com.hellokaton.blade.validator.Validators.i18nPrefix);
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals(\old(com.hellokaton.blade.validator.Validators.i18nPrefix.toString()));
    @ ensures msg.toString().equals(\old(msg.toString()));
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ ensures msg.toString().equals("\u4e0d\u662f\u4e00\u4e2a\u5408\u6cd5\u7684\u90ae\u7bb1");
    @*/
    /**
     * Determine if the input parameter is a Email. if yes, the check passes.
     *
     * @param msg error message after verification failed
     * @return Validation
     */
    public static Validation<String> isEmail(String msg) {
        return notEmpty().and(SimpleValidation.from(PatternKit::isEmail, msg));
    }

    /*@
    @ public normal_behavior // Generated by Daikon
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP == \old(com.hellokaton.blade.validator.Validators.I18N_MAP);
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName() == \old(com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName());
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix == \old(com.hellokaton.blade.validator.Validators.i18nPrefix);
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals(\old(com.hellokaton.blade.validator.Validators.i18nPrefix.toString()));
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ ensures \result != null;
    @*/
    /**
     * Determine if the input parameter is a URL. if yes, the check passes
     *
     * @return Validation
     */
    public static Validation<String> isURL() {
        return isURL(I18N_MAP.get(i18nPrefix + "IS_URL"));
    }

    /*@
    @ public normal_behavior // Generated by Daikon
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ requires com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ requires msg != null;
    @ requires msg.toString().equals("\u4e0d\u662f\u4e00\u4e2a\u5408\u6cd5\u7684URL");
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP == \old(com.hellokaton.blade.validator.Validators.I18N_MAP);
    @ ensures com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName() == \old(com.hellokaton.blade.validator.Validators.I18N_MAP.getClass().getName());
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix == \old(com.hellokaton.blade.validator.Validators.i18nPrefix);
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals(\old(com.hellokaton.blade.validator.Validators.i18nPrefix.toString()));
    @ ensures msg.toString().equals(\old(msg.toString()));
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix != null;
    @ ensures com.hellokaton.blade.validator.Validators.i18nPrefix.toString().equals("CN_");
    @ ensures msg.toString().equals("\u4e0d\u662f\u4e00\u4e2a\u5408\u6cd5\u7684URL");
    @ ensures \result != null;
    @*/
    /**
     * Determine if the input parameter is a URL. if yes, the check passes.
     *
     * @param msg error message after verification failed
     * @return Validation
     */
    public static Validation<String> isURL(String msg) {
        return notEmpty().and(SimpleValidation.from(PatternKit::isURL, msg));
    }

}
