#! /usr/bin/env bash

LOCAL=$(dirname "$BASH_SOURCE[0]" )
. "$LOCAL/../setup-script"

rm -rf MainApp.class actual
$BIN/openjml-compile MainApp.java > actual || exit 1
$BIN/openjml-run MainApp >> actual
diff actual expected && rm -rf actual
exit $?
