#! /bin/bash

cd $(dirname "$BASH_SOURCE")

if [ -e ../../../../openjml.github.io/tutorial ]; then
  (cd ../../../../openjml.github.io/tutorial; ./test )
  cp ../../../../openjml.github.io/tutorial/*.java  .
elif [ -e ../../../../../openjml.github.io/tutorial ]; then
  (cd ../../../../../openjml.github.io/tutorial; ./test )
  cp ../../../../../openjml.github.io/tutorial/*.java  .
fi
