#! /usr/bin/env bash

LOCAL=$(dirname "$BASH_SOURCE[0]" )
. "$LOCAL/../setup-script"

rm -rf *.class actual
openjml-compile Run.java || exit 1
openjml-run Run > actual || exit 1
openjml-java A >> actual || exit 1
diff actual expected && rm -rf actual
exit $?
