#! /usr/bin/env bash

LOCAL=$(dirname "$BASH_SOURCE[0]" )
. "$LOCAL/../setup-script"

rm -rf *.class actual
$BIN/openjml-compile Run.java || exit 1
$BIN/openjml-run Run > actual
$BIN/openjml-java A >> actual
diff actual expected && rm -rf actual
exit $?
