#! /bin/bash

cd $(dirname "$BASH_SOURCE[0]" )
BIN=../../../OpenJML21

rm -rf *.class actual
$BIN/openjml-compile Run.java || exit 1
$BIN/openjml-run Run > actual
$BIN/openjml-java A >> actual
diff actual expected

