#! /bin/bash

home=$(cd $(dirname $BASH_SOURCE) && pwd )
CMD=${home}/../../OpenJML21/openjml
ts=$(basename $1)

cd ${home}/../test
if [ ! -e $ts ]; then
    echo $ts : No such test
    exit 1
fi
if [ ! -d $ts ]; then
    exit 0;
fi
cd $ts


if [ -e skip ]; then
    echo Skipping $ts
elif [ -e rac ]; then
    echo Skipped-rac $ts
elif [ -e run ]; then
    echo Testing $ts
    ./run || echo test/$ts FAILED
else
    p=test/$ts
    if [ -e config ]; then . ./config; fi
    echo Testing $ts 
    cd ../..
    ## If you change the default FULLCMD, you may want to consider if the specialized versions in various test config files should be changed
    if [ -z "$FULLCMD" ]; then FULLCMD="$CMD $BASEARGS --specs-path $p $ARGS --dir $p"; fi
##  echo $FULLCMD
##: $FULLCMD
    $FULLCMD > $p/actual 2>&1
    stat=$?
    if [ ! -e $p/actual ]; then echo $p/actual : NO ACTUAL ; fi
    . $home/check-result $p/actual $stat && exit 1
fi
exit 0
