#! /bin/bash

## absolute path to directory containing this file
home=$(cd $(dirname $BASH_SOURCE) && pwd )
## Absolute path to source directory
SRC=${home}/../../OpenJML21
## Absolute path to OpenJMLTest
TEST=${home}/../../OpenJMLTest
## Absolute path to the openjml executable
CMD=$SRC/openjml
## Name of test and name of directory containing test (in $TEST/test)
testname=$(basename $1)

cd ${home}/../test
if [ ! -e $testname ]; then
    echo $testname : No such test
    exit 1
fi
if [ ! -d $testname ]; then
    exit 0;
fi
cd $testname

. $TEST/setup-coverage script-$testname


if [ -e skip ]; then
    echo Skipping $testname
elif [ -e rac ]; then ## rac tests are performed in unittests racfiles
    echo Skipped-rac $testname
elif [ -e run ]; then
    echo Testing $testname
    ./run || echo test/$testname FAILED
else
    p=test/$testname
    if [ -e config ]; then . ./config; fi
    echo Testing $testname 
    cd ../.. ## Now in $TEST
    ## If you change the default FULLCMD, you may want to consider if the specialized versions in various test config files should be changed
    if [ -z "$FULLCMD" ]; then FULLCMD="$CMD $BASEARGS --specs-path $p $ARGS --dir $p"; fi
##  echo $FULLCMD
##  $FULLCMD
    if [ -z "${AGENT}" ]; then
      $FULLCMD > $p/actual 2>&1
      stat=$?
    else
      ## To enable the coverage agent, we have to be running java (or openjml-java) not openjml
      ## so we run openjml indirectly through the programmatic api
      ##echo $SRC/openjml-java -cp . Run $BASEARGS --specs-path $p $ARGS --dir $p 
      $SRC/openjml-java -cp . Run $BASEARGS --specs-path $p $ARGS --dir $p > $p/actual 2>&1
      stat=$?
    fi
    if [ ! -e $p/actual ]; then echo $p/actual : NO ACTUAL ; fi
    . $home/check-result $p/actual $stat && exit 1
fi
exit 0
