#!/bin/bash

R=$( cd $(dirname $BASH_SOURCE)/../../..  && pwd)
OS=linux ## macosx linux windows aix
ROOT=$R/OpenJML/OpenJDKModule
BIN=$ROOT/build/*/jdk/bin/javac
SP=$ROOT/src/java.base/share/classes:$ROOT/build/*-server-release/support/gensrc/java.base:$ROOT/src/java.base/$OS/classes:$ROOT/src/java.base/unix/classes
AM="--add-modules jdk.compiler,java.base"
EXEC="-exec=$R/Solvers/Solvers-$OS/z3-4.3.1"

$BIN -no-internalSpecs -specspath .:$R/Specs/specs  "$@"
