#! /bin/bash

ntotal=$#
echo $ntotal "tests (some may be skipped)"
fs=( "$@" )

i=0
while [ $i -lt $ntotal ]; do

  ./sequential ${fs[$i]} &
  let "++i"

  nn=`jobs -r | wc -l`
  while [ $nn -ge $threads ]; do
    sleep 1
    nn=`jobs -r | wc -l`
  done

done

jobs -r
echo `jobs -r | wc -l` jobs running
wait
echo Completed
