#! /usr/bin/env bash

LOCAL=$(dirname "$BASH_SOURCE[0]" )
. "$LOCAL/../setup-script"

( \
echo Test of my.properties ;\
openjml --esc --properties=my.properties Test.java ;\
echo Test of openjml.properties ;\
openjml Test.java ;\
echo Test of bad.properties ;\
openjml --check --properties=bad.properties Test.java ;\
echo Test of no properties ;\
openjml --properties ;\
echo Test of folder ;\
openjml --properties folder --check Test.java ;\
echo Test of non-existent file ;\
openjml --properties zzz --check Test.java ;\
echo Test of mal-formed file ;\
openjml --properties=bad2.properties Test.java ;\
) >& actual
diff expected actual && rm -rf actual
exit $?
