#! /bin/bash

cd $(dirname $BASH_SOURCE[0] )  
BIN=../../../OpenJML21
if [ -z "$OJA" ]; then OJA=$BIN/openjml; fi

rm -rf Run.class actual
OJ=parse $BIN/openjml-compile *.java >& actual

LOC=`(cd ../../../..; pwd)`
sed -e "s%\$ROOT%$LOC%g" < expected | diff - actual && rm -rf actual
exit $?
