#! /usr/bin/env bash

LOCAL=$(dirname "$BASH_SOURCE[0]" )
. "$LOCAL/../setup-script"

rm -rf Run.class actual
OJ=parse openjml-compile *.java >& actual

LOC=`(cd ../../../..; pwd)`
sed -e "s%\$ROOT%$LOC%g" < expected | diff - actual && rm -rf actual
exit $?
