package com.hellokaton.blade.ioc.bean;

import com.hellokaton.blade.ioc.Injector;
import com.hellokaton.blade.ioc.Ioc;
import com.hellokaton.blade.kit.IocKit;

import java.lang.reflect.Field;

/**
 * Bean Field Injector
 *
 * @author <a href="mailto:hellokaton@gmail.com" target="_blank">hellokaton</a>
 * @since 1.5
 */
public class FieldInjector implements Injector {

    /*@ invariant this.ioc.getClass().getName() == com.hellokaton.blade.ioc.SimpleIoc.class.getName(); */
    public Ioc   ioc;
    public Field field;

    /*@
    @ public normal_behavior // Generated by Daikon
    @ requires ioc.getClass().getName() == com.hellokaton.blade.ioc.SimpleIoc.class.getName();
    @ ensures this.ioc == \old(ioc);
    @ ensures this.ioc.getClass().getName() == \old(ioc.getClass().getName());
    @ ensures this.field == \old(field);
    @*/
    public FieldInjector(Ioc ioc, Field field) {
        this.ioc = ioc;
        this.field = field;
    }

    /*@
    @ public normal_behavior // Generated by Daikon
    @ requires true;
    @*/
    public Class<?> getType() {
        return field.getType();
    }

    /*@
    @ public normal_behavior // Generated by Daikon
    @ requires true;
    @*/
    public boolean isSingleton() {
        return IocKit.isSingleton(field.getType());
    }

    /*@
    @ also
    @ public normal_behavior // Generated by Daikon
    @ requires this != null;
    @ requires this.ioc != null;
    @ requires this.field != null;
    @ requires bean != null;
    @ requires bean.getClass().getName() == com.hellokaton.blade.types.BladeBeanDefineType.class.getName();
    @ ensures this.ioc == \old(this.ioc);
    @ ensures this.ioc.getClass().getName() == \old(this.ioc.getClass().getName());
    @ ensures this.field == \old(this.field);
    @ ensures this.ioc != null;
    @ ensures this.field != null;
    @*/
    @Override
    public void injection(Object bean) {
        try {
            Class<?> fieldType = field.getType();
            Object   value     = ioc.getBean(fieldType);
            if (value == null) {
                throw new IllegalStateException("Can't inject bean: " + fieldType.getName() + " for field: " + field);
            }
            injection(bean, value);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    /*@
    @ also
    @ public normal_behavior // Generated by Daikon
    @ requires this != null;
    @ requires this.ioc != null;
    @ requires this.field != null;
    @ requires bean != null;
    @ requires bean.getClass().getName() == com.hellokaton.blade.types.BladeBeanDefineType.class.getName();
    @ requires value != null;
    @ requires value.getClass().getName() == java.lang.String.class.getName();
    @ ensures this.ioc == \old(this.ioc);
    @ ensures this.ioc.getClass().getName() == \old(this.ioc.getClass().getName());
    @ ensures this.field == \old(this.field);
    @ ensures this.ioc != null;
    @ ensures this.field != null;
    @*/
    @Override
    public void injection(Object bean, Object value) {
        try {
            field.setAccessible(true);
            field.set(bean, value);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    /*@
    @ public normal_behavior // Generated by Daikon
    @ requires true;
    @*/
    public boolean hasInjectFields() {
        return field.getType().getDeclaredFields().length > 0;
    }

}
