/**
 * Copyright (c) 2018, biezhi nice (hellokaton@gmail.com)
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.hellokaton.blade.validator;

import lombok.AllArgsConstructor;

import java.util.function.Predicate;

@AllArgsConstructor
public class SimpleValidation<T> implements Validation<T> {

    public Predicate<T> predicate;
    public String       onErrorMessage;

    /*@
    @ public normal_behavior // Generated by Daikon
    @ requires predicate != null;
    @ requires onErrorMessage != null;
    @ ensures onErrorMessage.toString().equals(\result.onErrorMessage.toString());
    @ ensures onErrorMessage.toString().equals(\old(onErrorMessage.toString()));
    @ ensures \result.predicate == \old(predicate);
    @ ensures \result.predicate.getClass().getName() == \old(predicate.getClass().getName());
    @ ensures \result.onErrorMessage == \old(onErrorMessage);
    @ ensures \result != null;
    @ ensures \result.predicate != null;
    @ ensures \result.onErrorMessage != null;
    @*/
    public static <T> SimpleValidation<T> from(Predicate<T> predicate, String onErrorMessage) {
        return new SimpleValidation<>(predicate, onErrorMessage);
    }

    /*@
    @ public normal_behavior // Generated by Daikon
    @ requires this.predicate.getClass().getName() != param.getClass().getName();
    @ ensures this.predicate == \old(this.predicate);
    @ ensures this.predicate.getClass().getName() == \old(this.predicate.getClass().getName());
    @ ensures this.onErrorMessage == \old(this.onErrorMessage);
    @ ensures this.onErrorMessage.toString().equals(\result.message.toString());
    @ ensures this.onErrorMessage.toString().equals(\old(this.onErrorMessage.toString()));
    @ ensures \result != null;
    @ ensures \result.code == null;
    @ ensures this.predicate.getClass().getName() != \old(param.getClass().getName());
    @*/
    @Override
    public ValidationResult test(T param) {
        return predicate.test(param) ? ValidationResult.ok() : ValidationResult.fail(onErrorMessage);
    }

}
