#! /bin/bash

if [ "$(uname)" != "Darwin" ]; then
    echo "This script is for macOS only." >&2
    exit 1
fi

## This is run to fix some Mac security warnings
## It actually only needs to be run once; it emits errors on subsequent runs.

cd "$(dirname $BASH_SOURCE)"
xattr -d com.apple.quarantine `find . -name java` `find . -name *.dylib` `find . -name javac` `find . -name  *z3*` `find . -name *cvc*` `find . -name jspawnhelper`
