#! /usr/bin/env bash

## This script tests the behavior of the -d option for --show=json and --show=typed-json

## Might have trouble with symbolic links
cd $(dirname "${BASH_SOURCE[0]}")

ERR=0

. ../../setup-coverage jsonloc
mkdir -p ../../cov

echo JSON output location tests
rm -rf *.json
openjml --show=json *.java
for f in *.java ; do
  if ! diff $f.json $f.json.expected ; then ERR=1 ; echo $f.json differs from expected; fi; 
done

echo JSON A
rm -rf *.json
openjml --show=json -d - *.java > out
cat Test*.json.expected | diff - out

echo JSON B
rm -rf *.json out xx
openjml --show=json -d xx/yy *.java
if ! diff xx/yy/Test.java.json Test.java.json.expected ; then ERR=1 ; echo xx/yy/Test.java.json differs from expected ; fi;
if ! diff xx/yy/p/TestP.java.json TestP.java.json.expected ; then ERR=1 ; echo xx/yy/p/TestP.java.json differs from expected; fi;
if ! diff xx/yy/q/r/TestPP.java.json TestPP.java.json.expected ; then ERR=1 ; echo xx/yy/q/r/TestPP.java.json differs from expected ; fi;
echo "xxx" >> xx/yy/Test.java.json

# repeat without deleting files, to test ability to overwrite
echo JSON C 
openjml --show=json -d xx/yy *.java
diff xx/yy/Test.java.json Test.java.json.expected || ERR=1
diff xx/yy/p/TestP.java.json TestP.java.json.expected || ERR=1
diff xx/yy/q/r/TestPP.java.json TestPP.java.json.expected || ERR=1

rm -rf xx
if [ $ERR == 1 ]; then echo "JSON LOCATION TESTS FAILED "; fi
exit $ERR

################### Not testing typed ASTs yet

## Typed AST
echo TYPED
rm -rf *.json
penjml --show=typed-json *.java
for f in A.json C.json CC.json CCC.json ; do
  echo CHECKING $f
  if ! diff $f $f.expected ; then ERR=1 ; echo $f differs from expected ; else rm -rf $f; fi;
done
exit $ERR
penjml --show=typed-json -d - *.java > out
if ! ( cat [AC]*.expected | diff - out ) ; then ERR=1 ; echo 'AC* differs from expected' ; else rm -rf out; fi;

rm -rf out xx
penjml --show=typed-json -d xx/yy *.java
if ! diff xx/yy/A.json A.json.expected ; then ERR=1 ; echo xx/yy/A.json differs from expected ; fi;
if ! diff xx/yy/C.json C.json.expected ; then ERR=1 ; echo xx/yy/C.json differs from expected ; fi;
if ! diff xx/yy/p/CC.json CC.json.expected ; then ERR=1 ; echo xx/yy/p/CC.json differs from expected ; fi;
if ! diff xx/yy/q/r/CCC.json CCC.json.expected ; then ERR=1 ; echo xx/yy/q/r/CCC.json differs from expected ; fi;
echo "xxx" >> xx/yy/Test.java.json
# repeat without deleting files
penjml --show=typed-json -d xx/yy *.java
if ! diff xx/yy/A.json A.json.expected ; then ERR=1 ; echo xx/yy/A.json differs from expected ; fi;
if ! diff xx/yy/C.json C.json.expected ; then ERR=1 ; echo xx/yy/C.json differs from expected ; fi;
if ! diff xx/yy/p/CC.json CC.json.expected ; then ERR=1 ; echo xx/yy/p/CC.json differs from expected ; fi;
if ! diff xx/yy/q/r/CCC.json CCC.json.expected ; then ERR=1 ; echo xx/yy/q/r/CCC.json differs from expected ; fi;

if [ $ERR == 1 ]; then echo "JSON LOCATION TESTS FAILED "; fi
exit $ERR
