#! /bin/bash

## The directory containing this file, which should be either .../OpenJML21 or the release folder
LOCAL=$( cd $(dirname "$BASH_SOURCE") && pwd)

. $LOCAL/setup-exports

## Now run the compiled Test program
"$LOCAL/openjml-java" $EXPORTS "$@"

