#!/bin/bash

## This is for the development environment
## It is a convenience script to run the version of 'java' embellished with openjml's runtime libraries

R1=$(realpath "$BASH_SOURCE" ) ## realpath needed to resolve symlinks; R1 will be the path to this file
R2=$(dirname "$R1") # path of the folder containing this file
R=$( cd "$R2/../.."  && pwd) ## absolute path of the grandparent folder (that holds clones of all the relevant repos), still might have spaces

##OS=linux ## macosx linux windows aix
ROOT="$R/OpenJML/OpenJML21"
BIN=`echo $ROOT/build/*/jdk/bin/java`

OPENJML_ROOT="$R/Solvers" "$BIN" "$@"

