#! /bin/bash
## This script runs the basic openjml compilation/esc/rac tool, but with the options that permit linking in 
## openjdk/openjml code for programmatic access to openjdk/openjml. It is analogous to javac.

## This script may be executed within the development environment or in a release

## Directory containing this file, which should be either .../OpenJML21 or the release folder
FILE=$(realpath "$BASH_SOURCE" ) ## realpath needed to resolve symlinks -- result is the path to this script file
LOCAL=$(dirname "$FILE") # path of the folder containing this file

if [ -e "$LOCAL/version-info.txt" ]; then
  ## In a release
  CL=`echo $LOCAL/jdk/modules/*  | grep -v META | sed -e "s/ /:/g"`
  MODULES="$LOCAL/jdk/modules"
else
  ## In development environment
  CL=`echo $LOCAL/build/*/jdk/modules/*  | grep -v META | sed -e "s/ /:/g"`
  MODULES=`echo "$LOCAL"/build/*release/jdk/modules`
fi

CP=".:$CL"

. $LOCAL/setup-exports

"$LOCAL/openjml" -cp "$CP" -p $MODULES $EXPORTS --compile "$@"

