#! /bin/bash 

# Go to OpenJMLTest
cd $(dirname "$BASH_SOURCE")/..

## This file tests a release of the OpenJML tool
## This is just a quick "smoke" test to make sure that 
## the tool runs on simple inputs
## It is intended to be run with the OpenJML project directory as its 
## current working directory, but does its work in a temporary subdirectory

## Name of folder holding releaseBuilds (within OpenJML)


Z=:
if [[ "$COMSPEC" != "" ]] ; then
Z=';'
fi

cd ../OpenJMLTest

rm -rf temp-release
mkdir temp-release
cd temp-release

if [ -z ${NOZIP+x} ]; then
## if NOZIP is not set, then test the most recent release zip

ZIP=../../OpenJDKModule/release-temp/openjml.zip
if [ -e "$ZIP" ]; then
  cp $ZIP .
else
  echo "Zip file not found" $ZIP "cwd=" `pwd` 
  exit 1
fi
  
unzip openjml.zip > /dev/null
OJ=`pwd`/openjml

elif [ -z "$OJ" ]; then
## NOZIP was set to a null string; test the current build

OJ=`pwd`/../../OpenJDKModule/openjml
echo "Testing current build at $OJ"

else
## NOZIP was set to something, use that as the openjml to test

OJ="$NOZIP"
echo "Testing executable at $OJ"

fi

TESTLOC=../releaseTests

if [ ! -e "$OJ" ]; then
   echo No openjml : $OJ
   exit 1
fi

export RTH=../releaseTests/releaseTestHelper
RES=0


## Checks the version
echo Visually check that the version matches the zip file being tested
$OJ -version
echo "openjml" `cat ../../version.txt` > ${TESTLOC}/testJmlVersion/expected
${RTH} testJmlVersion "$OJ -version" || RES=$(($RES+1))


## Checks the help message (when there are no arguments)
${RTH} testJmlHelpSimp "$OJ" || RES=$(($RES+1))

## Checks the help message (when there is a -help option)
${RTH} testJmlHelp "$OJ -?" || RES=$(($RES+1))

## Checks the help message (when there is a -help option)
${RTH} testJmlHelp "$OJ -help" || RES=$(($RES+1))

## Checks when there is a bad verboseness argument ## FIXME - embedded quotes are not working as expected within the test script
##${RTH} testJmlBad "$OJ -verboseness \"\"" || RES=$(($RES+1))

## Checks when there is a bad verboseness argument
${RTH} testJmlBad "$OJ -verboseness=" || RES=$(($RES+1))

## Checks when there is a bad verboseness property
export OPENJML_verboseness=x
${RTH} testJmlBad2 "$OJ -check" || RES=$(($RES+1))
unset OPENJML_verboseness

## Checks when there is a bad verboseness property
echo "org.openjml.option.verboseness=x" > ./openjml.properties
${RTH} testJmlBad2 "$OJ -check" || RES=$(($RES+1))
rm openjml.properties

## Checks when there is a bad use of -java
${RTH} testJmlBad3 "$OJ -check -java" || RES=$(($RES+1))

## Checks when there is a bad verboseness argument ## FIXME _ this works OK but not within this test script
#${RTH} testJmlBad "$OJ '-verboseness= '" || RES=$(($RES+1))



echo "public class A { /*@ invariant 0; */ }" > A.java
echo "public class B { /*@ invariant true; */ }" > B.java
echo "import org.jmlspecs.annotation.Pure; public class C { @Pure int m() { return 0; } }" > C.java
echo "import org.jmlspecs.annotation.*; public class D { @Pure int m() { return 0; } }" > D.java


## Checks a valid file using java -jar
${RTH} testOK1 "$OJ -noPurityCheck -specspath . B.java" || RES=$(($RES+1))

echo SKIPPING RAC
## FIXME
if [[ "SKIP" == "" ]]; then

## rac
rm -rf rac
mkdir -p rac
${RTH} testRac "$OJ -rac -noRacSource -noPurityCheck -d rac -classpath ../testfiles/testRac -specspath ../testfiles/testRac ../testfiles/testRac/A.java" || { RES=$(($RES+1)); }
echo RAC-OK
#echo java -classpath "rac${Z}jmlruntime.jar" A
java -classpath "rac${Z}jmlruntime.jar" A  > racactual
tr -d '\r' < racactual |  diff - ../releaseTests/testRac/expected-ok || { RES=$(($RES+1)); }
echo RAC-SIMPLE
java -classpath "rac${Z}jmlruntime.jar" A 1 2  > racactual
tr -d '\r' < racactual | sed -e 'sx\\x/xg' | diff - ../releaseTests/testRac/expected-simple || { RES=$(($RES+1)); }
echo RAC-EXC
java -classpath "rac${Z}jmlruntime.jar" -Dorg.jmlspecs.openjml.racexceptions A 1 2 > racactual  2>&1
tr -d '\r' < racactual | sed -e 'sx\\x/xg' |  diff - ../releaseTests/testRac/expected-exceptions || { RES=$(($RES+1)); }
echo RAC-BOTH
java -classpath "rac${Z}jmlruntime.jar" -Dorg.jmlspecs.openjml.racexceptions -Dorg.jmlspecs.openjml.racshowstack A 1 2   > racactual  2>&1
tr -d '\r' < racactual | sed -e 'sx\\x/xg' |  diff - ../releaseTests/testRac/expected-exceptions || { RES=$(($RES+1)); }
echo RAC-ST
java -classpath "rac${Z}jmlruntime.jar" -Dorg.jmlspecs.openjml.racshowstack A 1 2 > racactual
tr -d '\r' < racactual | sed -e 'sx\\x/xg' |  diff - ../releaseTests/testRac/expected-stack || { RES=$(($RES+1)); }

fi


## This checks verbose output - which changes too often to put in the 
## regular test suite
if [[ "$COKENV" != "" ]] ; then
## Checks a valid file with jmlverbose
${RTH} testOK3 "$OJ -noPurityCheck -specspath . B.java -jmlverbose" || RES=$(($RES+1))
fi

## Checks a valid file with no internal specs
## FIXME - why does this work?
${RTH} testOK4 "$OJ -specspath . B.java -noInternalSpecs" || RES=$(($RES+1))

## Checks a valid file with no internal runtime library - should fail to find annotations
## FIXME - is -noInternalRuntime still a usefule/vlid option?
${RTH} testRuntime1 "$OJ C.java -jmltesting -classpath . -noPurityCheck -noInternalRuntime" || RES=$(($RES+1))

## ANNOTATIONS might be an absolute or relative path.  We are currently in
## OpenJML/temp-release so if absolute we want ${ANNOTATIONS}, if relative we want ../${ANNOTATIONS}

#if [ ! -e ${ANNOTATIONS} ]; then
ANNOTATIONS=../../../JMLAnnotations
#fi

## FIXME - uses of OpenJML/bin-runtime must change
## Checks a valid file with an external binary runtime library - should be OK
${RTH} testRuntime2 "$OJ C.java -noPurityCheck -classpath ../../OpenJML/bin-runtime${Z}${ANNOTATIONS}/bin -noInternalRuntime"  || RES=$(($RES+1))

## Checks a valid file with an external source runtime library - should be OK
${RTH} testRuntime3 "$OJ C.java -noPurityCheck -classpath ../../OpenJML/runtime${Z}${ANNOTATIONS}/src -noInternalRuntime" || RES=$(($RES+1))

## Checks using annotations with normal use - should be OK
${RTH} testRuntime4 "$OJ C.java -noPurityCheck " || RES=$(($RES+1))

## Checks using annotations with normal use - should be OK
${RTH} testRuntime5 "$OJ D.java -noPurityCheck " || RES=$(($RES+1))

## Checks using classpath - ok, uses specs in java file
${RTH} testEsc1 "$OJ -noPurityCheck -esc ../testfiles/testEsc/A.java -classpath ../testfiles/testEsc" || RES=$(($RES+1))

## Checks using classpath - ok, uses specs in java file
${RTH} testEsc2 "$OJ -noPurityCheck -esc ../testfiles/testEsc/B.java -classpath ../testfiles/testEsc" || RES=$(($RES+1))


## Checks using no paths - fails to find super class, uses specs in java file
${RTH} testPath1 "$OJ -jmltesting -noPurityCheck ../testfiles/testPath/data/TestPath.java " || RES=$(($RES+1))

## Checks using classpath - ok, uses specs in java file
${RTH} testPath2 "$OJ -jmltesting -noPurityCheck ../testfiles/testPath/data/TestPath.java -classpath ../testfiles/testPath/data" || RES=$(($RES+1))

## Checks using specs path - finds specs but not super class
${RTH} testPath3 "$OJ -jmltesting -noPurityCheck ../testfiles/testPath/data/TestPath.java -specspath ../testfiles/testPath/data-specs " || RES=$(($RES+1))

## Checks using source path - finds specs but not super class
${RTH} testPath4 "$OJ -jmltesting -noPurityCheck ../testfiles/testPath/data/TestPath.java -sourcepath ../testfiles/testPath/data-specs " || RES=$(($RES+1))

## Checks using source path (specs and java) - finds specs and super class
${RTH} testPath5 "$OJ -jmltesting -noPurityCheck ../testfiles/testPath/data/TestPath.java -sourcepath ../testfiles/testPath/data-specs${Z}../testfiles/testPath/data " || RES=$(($RES+1))

## Checks using source path (java then specs) - finds super class; uses jml file for specs even though it is later on the search path
${RTH} testPath6 "$OJ -jmltesting -noPurityCheck ../testfiles/testPath/data/TestPath.java -sourcepath ../testfiles/testPath/data${Z}../testfiles/testPath/data-specs" || RES=$(($RES+1))

## Checks using source path and specs path - uses specs file, finds super class
${RTH} testPath7 "$OJ -jmltesting -noPurityCheck ../testfiles/testPath/data/TestPath.java -sourcepath ../testfiles/testPath/data -specspath ../testfiles/testPath/data-specs" || RES=$(($RES+1))

## Checks using class path (specs and java) - finds specs and super class
${RTH} testPath8 "$OJ -jmltesting -noPurityCheck ../testfiles/testPath/data/TestPath.java -classpath ../testfiles/testPath/data-specs${Z}../testfiles/testPath/data " || RES=$(($RES+1))

## Checks using class path (java then specs) - finds super class; uses jml file for specs
${RTH} testPath9 "$OJ -jmltesting -noPurityCheck ../testfiles/testPath/data/TestPath.java -classpath ../testfiles/testPath/data${Z}../testfiles/testPath/data-specs" || RES=$(($RES+1))

## Checks using class path and specs path - uses specs file, finds super class
${RTH} testPath10 "$OJ -jmltesting -noPurityCheck ../testfiles/testPath/data/TestPath.java -classpath ../testfiles/testPath/data -specspath ../testfiles/testPath/data-specs" || RES=$(($RES+1))


## FIXME - this gives an odd error message.  The presence/absence of rt.jar makes no difference
##   adding additional spec files or removing -noInternalSpecs gets past this error, but not sure why
##   also why would runtime be in the specs path?
#$OJ -classpath "../bin" -sourcepath ../testfiles/testNoErrors -specs "../runtime" -noPurityCheck -noInternalSpecs ../testfiles/testNoErrors/A.java || { RES=$(($RES+1)); }


## Checks an invalid file
${RTH} testCheck1 "$OJ -jmltesting -noPurityCheck -specspath . A.java" || RES=$(($RES+1))


## FIXME - jmldoc & prettyprinying
if [[ "SKIP" == "" ]]; then

export DIFFJMLDOC="diff -r "

### Note: package-tree.html is excluded because it is non-deterministic

## checks jmldoc prettyprinting
rm -rf doc ../testfiles/prettyprint/actual
${RTH} testJmldocPP "java -classpath openjml.jar org.jmlspecs.openjml.jmldoc.Main -d doc -private -notimestamp -noPurityCheck ../testfiles/prettyprint/data/PP.java " || { RES=$(($RES+1)); }
${DIFFJMLDOC} -x '.svn' -x 'package-tree.html' doc ../testfiles/prettyprint/expected || { RES=$(($RES+1)); rm -rf ../testfiles/prettyprint/actual; mv doc ../testfiles/prettyprint/actual; }

## jmldoc check
rm -rf doc ../testfiles/jmldoc1/actual
${RTH} testJmldoc "java -classpath openjml.jar org.jmlspecs.openjml.jmldoc.Main -d doc -notimestamp -noPurityCheck ../testfiles/jmldoc1/data/*.java " || { RES=$(($RES+1)); }
${DIFFJMLDOC} -x '.svn' -x 'package-tree.html' doc ../testfiles/jmldoc1/expected || { RES=$(($RES+1)); rm -rf ../testfiles/jmldoc1/actual; mv doc ../testfiles/jmldoc1/actual; }

## jmldoc - checking the -java flag; uses the jmldoc3 input data
rm -rf doc ../testfiles/jmldoc2/actual
export NOSTDDOCLET=1
${RTH} testJmldoc2 "java -classpath openjml.jar org.jmlspecs.openjml.jmldoc.Main -java -d doc -public -notimestamp -noPurityCheck ../testfiles/jmldoc3/data/*.java ../testfiles/jmldoc3/data/tp/*.java" || { RES=$(($RES+1)); }
${DIFFJMLDOC} -x '.svn' -x 'package-tree.html' doc ../testfiles/jmldoc2/expected || { RES=$(($RES+1)); mv doc ../testfiles/jmldoc2/actual; }
export NOSTDDOCLET=

## jmldoc - checking the -public flag
rm -rf doc ../testfiles/jmldoc3/actual
${RTH} testJmldoc3 "java -classpath openjml.jar org.jmlspecs.openjml.jmldoc.Main -d doc -public -notimestamp -noPurityCheck ../testfiles/jmldoc3/data/*.java ../testfiles/jmldoc3/data/tp/*.java" || { RES=$(($RES+1)); }
${DIFFJMLDOC} -x '.svn' -x 'package-tree.html' doc ../testfiles/jmldoc3/expected || { RES=$(($RES+1)); mv doc ../testfiles/jmldoc3/actual; }

## jmldoc - checking the -protected flag - purposely uses the jmldoc3 data
rm -rf doc ../testfiles/jmldoc4/actual
${RTH} testJmldoc4 "java -classpath openjml.jar org.jmlspecs.openjml.jmldoc.Main -d doc -protected -notimestamp -noPurityCheck ../testfiles/jmldoc3/data/*.java ../testfiles/jmldoc3/data/tp/*.java" || { RES=$(($RES+1)); }
${DIFFJMLDOC} -x '.svn' -x 'package-tree.html' doc ../testfiles/jmldoc4/expected || { RES=$(($RES+1)); mv doc ../testfiles/jmldoc4/actual; }

## jmldoc - checking the -package flag - purposely uses the jmldoc3 data
rm -rf doc ../testfiles/jmldoc5/actual
${RTH} testJmldoc5 "java -classpath openjml.jar org.jmlspecs.openjml.jmldoc.Main -d doc -package -notimestamp -noPurityCheck ../testfiles/jmldoc3/data/*.java ../testfiles/jmldoc3/data/tp/*.java" || { RES=$(($RES+1)); }
${DIFFJMLDOC} -x '.svn' -x 'package-tree.html' doc ../testfiles/jmldoc5/expected || { RES=$(($RES+1)); mv doc ../testfiles/jmldoc5/actual; }

## jmldoc - checking the -private flag - purposely uses the jmldoc3 data
rm -rf doc ../testfiles/jmldoc6/actual
${RTH} testJmldoc6 "java -classpath openjml.jar org.jmlspecs.openjml.jmldoc.Main -d doc -private -notimestamp -noPurityCheck ../testfiles/jmldoc3/data/*.java ../testfiles/jmldoc3/data/tp/*.java" || { RES=$(($RES+1)); }
${DIFFJMLDOC} -x '.svn' -x 'package-tree.html' doc ../testfiles/jmldoc6/expected || { RES=$(($RES+1)); mv doc ../testfiles/jmldoc6/actual; }


## jmldoc - checking the -private flag - purposely uses the jmldoc3 data
rm -rf doc ../testfiles/jmldoc7/actual
${RTH} testJmldoc7 "java -classpath openjml.jar org.jmlspecs.openjml.jmldoc.Main -d doc -private -notimestamp -noPurityCheck -dir ../testfiles/jmldoc3/data -dir ../testfiles/jmldoc3/data/tp" || { RES=$(($RES+1)); }
${DIFFJMLDOC} -x '.svn' -x 'package-tree.html' doc ../testfiles/jmldoc7/expected || { RES=$(($RES+1)); mv doc ../testfiles/jmldoc7/actual; }

## jmldoc - checking the -private flag - purposely uses the jmldoc3 data
rm -rf doc ../testfiles/jmldoc7/actual
${RTH} testJmldoc7 "java -classpath openjml.jar org.jmlspecs.openjml.jmldoc.Main -d doc -private -notimestamp -noPurityCheck -dirs ../testfiles/jmldoc3/data ../testfiles/jmldoc3/data/tp" || { RES=$(($RES+1)); }
${DIFFJMLDOC} -x '.svn' -x 'package-tree.html' doc ../testfiles/jmldoc7/expected || { RES=$(($RES+1)); mv doc ../testfiles/jmldoc7/actual; }

## jmldoc - checking the -private flag - purposely uses the jmldoc3 data
rm -rf doc ../testfiles/jmldoc7/actual
${RTH} testJmldoc7 "java -classpath openjml.jar org.jmlspecs.openjml.jmldoc.Main -d doc -private -noPurityCheck -dirs ../testfiles/jmldoc3/data ../testfiles/jmldoc3/data/tp  -notimestamp" || { RES=$(($RES+1)); }
${DIFFJMLDOC} -x '.svn' -x 'package-tree.html' doc ../testfiles/jmldoc7/expected || { RES=$(($RES+1)); mv doc ../testfiles/jmldoc7/actual; }





fi

if [[ ${RES} -eq 0 ]]; then echo "All tests succeeded"; else echo ${RES} tests failed  ; fi


cd ..
##rm -rf temp-release
exit ${RES}
