#! /usr/bin/env bash

LOCAL=$(dirname "$BASH_SOURCE[0]" )
. "$LOCAL/../setup-script"

rm -rf Run.class actual
openjml-compile Run.java > actual || exit 1
openjml-run Run >> actual         || exit 1
diff actual expected && rm -rf actual Run.class
exit $?
