#! /bin/bash

cd $(dirname "$BASH_SOURCE[0]" )
BIN=../../../OpenJML21
if [ -z "$OJA" ]; then OJA=$BIN/openjml; fi

rm -rf Run.class actual
$BIN/openjml-compile Run.java > actual || exit 1
$BIN/openjml-run Run >> actual
diff actual expected && rm -rf actual Run.class
exit $?
