#! /usr/bin/env bash

cd $(dirname $BASH_SOURCE[0])
if [ -z "$OJBIN" ] ; then
  OJBIN=../../../OpenJMLsrc
fi

rm -rf *.class
"$OJBIN/openjml-compile" Run.java
"$OJBIN/openjml-run" Run --esc A.java
"$OJBIN/openjml-run" Run --rac A.java
"$OJBIN/openjml-java" A
exit 0
