#! /usr/bin/env bash

## Might have trouble with symbolic links
cd $(dirname "${BASH_SOURCE[0]}")

ERR=0
DIRS=$@
if [ ${#DIRS} == 0 ] ; then DIRS=* ; fi

for d in $DIRS ; do 
  if [ -d $d ]; then
  echo DIR $d
  openjml --show=json $d/*.java
  for j in $d/*.json; do
    ( diff $j $j.expected && rm $j ) || ERR=1
  done
  fi
done

if [ $ERR == 1 ] ; then echo JSON TESTS FAILED; fi
exit $ERR
