name: 'OpenJML Build'
description: 'A composite action that builds OpenJML in an existing check out'

## Presumes the current working folder is the one containsing OpenJML, Specs, Solvers, JMLAnnotations etc.

inputs:
  test:
    description: 'Whether to run the release test'
    type: boolean
    required: true

runs:
  using: 'composite'
  steps:
    ## The expected working directory is OpenJML, that is, the folder that holds OpenJMLsrc
    - name: Build OpenJML release on Windows
      if: runner.os == 'Windows'
      shell: wsl-bash {0}
      run: |
        cd OpenJML/OpenJMLsrc
        ./configure
        make release
        cd ..
    - name: Build OpenJML release on non-Windows
      if: runner.os != 'Windows'
      shell: bash
      run: |
        cd OpenJML/OpenJMLsrc
        ./configure
        make release
        cd ..
    - name: Test the build
      if: inputs.test == 'true'
      shell: bash
      run: |
        make -C OpenJML/OpenJMLsrc release-test
