#! /usr/bin/env bash

LOCAL=$(dirname "$BASH_SOURCE[0]" )
. "$LOCAL/../setup-script"

rm -rf *.class */*.class
(\
echo Test 1 uses B.java from . ;\
openjml -cp . --esc A.java ;\
echo Test 2 uses B.java from srcp ;\
openjml -cp . --source-path srcp --esc A.java ;\
echo Test 2a cannot find B.java ;\
openjml -cp . --source-path srce --esc A.java ;\
echo Test 3 uses B.java from .;\
openjml -cp . --esc srcx/A.java ;\
echo Test 4 uses B.java from srcp ;\
openjml -cp . --source-path srcp --specs-path srce --esc srcx/A.java ;\
echo Test 4a cannot find B.java;\
openjml -cp . --source-path srce --specs-path srce --esc srcx/A.java ;\
) >& actual

diff expected actual && rm -rf actual
exit $?
