#! /bin/bash

cd $(dirname $BASH_SOURCE[0] )  
BIN=../../../OpenJML21
if [ -z "$OJA" ]; then OJA=$BIN/openjml; fi

(\
echo Test 1 uses B.java from . ;\
$OJA --esc A.java ;\
echo Test 2 uses B.java from srcp ;\
$OJA --source-path srcp --esc A.java ;\
echo Test 2a cannot find B.java ;\
$OJA --source-path srce --esc A.java ;\
echo Test 3 uses B.java from .;\
$OJA --esc srcx/A.java ;\
echo Test 4 uses B.java from srcp ;\
$OJA --source-path srcp --specs-path srce --esc srcx/A.java ;\
echo Test 4a cannot find B.java;\
$OJA --source-path srce --specs-path srce --esc srcx/A.java ;\
) >& actual
diff expected actual && rm -rf actual
