name: Nightly test of OpenJML

## This workflow runs all the unit and functionality tests on a build of the current developmenet environment for OpenJML
## that is, on the HEAD of branch dev-21 as it has been pushed to the github repo.
## The workflow runs each designated OS as a separate matrixed job. The job does a build and then sequentially runs a number of tests.
##
## The disadvantage of this design is that the various test tasks are run sequentially. If one fails, the rest are not tested.
## But if we mark them to continue on error in some way, they do not show up as failed in the workflow summary.
##
## A different design would put the test tasks in separate jobs, which could then run concurrently. However this requires
## either doing a full build for each of these test tasks, which is time consuming, or uploading and downloading a github artifact that
## contained the full built repo checkout. This latter 'worked' but frequently failed because the artifacts took too much space.
##
## As a compromise, two jobs are used: one jobs builds OpenJLM and runs the very long-running unit tests; the other builds OpenJLM are runs 
## the other, shorter running, test suites.

## FIXME: The setting of PATH uses : where it might need ; for some OSes; it would be better if adjustments to PATH were not needed at all
## FIXME: debug use of the $sep variable

on:
  workflow_dispatch:
  push:
    branches: [ dev-21 ]
#  schedule:
#    - cron: "0 0 * * *"

env:
  ## Branch to build from (both in OpenJML and Specs). (JMLAnnotation, Solvers, openjml.github.io are fixed to be 'master')
  ## The github branch that was pushed
  BRANCH: ${{ github.ref_name }}
  ## Name of folder containing openjml code within OpenJML repo. Ought to match the triggering branch in 'on push'.
  FOLDER: OpenJMLsrc

jobs:

  export-matrix:
    runs-on: ubuntu-latest
    outputs:
      oses: ${{ steps.export.outputs.oslist }}
    steps:
    - id: export
      run: |
        ## Edit the list of OSes here
        echo 'oslist=[ "macos-14", "ubuntu-22.04", "ubuntu-latest" ]' >> "$GITHUB_OUTPUT"
    
  ## This job builds a development version of OpenJML as part of a trial release build
  ## and then runs various unit and functionality tests
  othertests:
    needs: export-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ fromJson(needs.export-matrix.outputs.oses) }}
      fail-fast: false

    steps:
    - name: Checkout actions
      uses: actions/checkout@v4
      with:
        sparse-checkout: ./.github
        path: ACTIONS
    - name: OS setup
      uses: ./ACTIONS/.github/actions/os-setup/

    - name: Checkout OpenJML
      uses: ./ACTIONS/.github/actions/openjml-checkout/
      with:
        branch: ${{ github.ref_name }}

    - name: Build OpenJML
      uses: ./ACTIONS/.github/actions/openjml-build/
      with:
        ## These tests of the release are performed in the build workflow
        test: false

    - name: Variable
      run: |
        echo $sep $sepsemi
        PATH="../../OpenJML/$FOLDER$sep$PATH" echo $PATH
        PATH="../../OpenJML/$FOLDER$sepsemi$PATH" echo $PATH
        echo "failures=" >> $GITHUB_ENV

    - name: Run userguide tests
      run: |
        cd OpenJML/OpenJMLTest
        git clone https://git:${{ secrets.OVERLEAF_TOKEN }}@git.overleaf.com/620c2512d552cc226f5f4c94
        cd 620c2512d552cc226f5f4c94
        chmod +x test-userguide-examples
        ./test-userguide-examples || echo "failures=$failures userguide tests failed." >> $GITHUB_ENV

    - name: Run release tests
      run: |
        PATH="../../$FOLDER$sep$PATH" make -C OpenJML/OpenJMLTest release-tests || echo "failures=$failures release tests failed." >> $GITHUB_ENV

    - name: Run tutorial tests
      run: |
        PATH="../../OpenJML/$FOLDER$sep$PATH" make -C OpenJML/OpenJMLTest tutorial-tests-git || echo "failures=$failures tutorial tests failed." >> $GITHUB_ENV

    - name: Run json tests
      run: |
        PATH="../../../$FOLDER$sep$PATH" make -C OpenJML/OpenJMLTest json-tests || echo "failures=$failures json tests failed." >> $GITHUB_ENV

    - name: Report
      run: |
        if [ -z "$failures" ] ; then echo All tests OK; exit 0; else echo $failures; exit 1; fi
        

  ## This job builds a development version of OpenJML as part of a trial release build
  ## and then runs various unit and functionality tests
  unittests:
    needs: export-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ fromJson(needs.export-matrix.outputs.oses) }}
      fail-fast: false

    steps:
    - name: Checkout actions
      uses: actions/checkout@v4
      with:
        sparse-checkout: ./.github
        path: ACTIONS
    - name: OS setup
      uses: ./ACTIONS/.github/actions/os-setup/
    - name: Checkout OpenJML
      uses: ./ACTIONS/.github/actions/openjml-checkout/
      with:
        branch: ${{ github.ref_name }}
    - name: Build OpenJML
      uses: ./ACTIONS/.github/actions/openjml-build/
      with:
        test: false ## These tests of the release are performed in the build workflow

    - name: Run unit tests
      run: |
        PATH="../../$FOLDER$sep$PATH" make -C OpenJML/OpenJMLTest unittests-par 


