name: Nightly test of  OpenJML

on:
  workflow_dispatch:
  push:
    branches: [ dev-21 ]
#  schedule:
#    - cron: "0 0 * * *"

env:
  ## Branch to build from (both in OpenJML and Specs). (JMLAnnotation, Solvers, openjml.github.io are fixed to be 'master')
  ## The github branch that was pushed
  BRANCH: ${{ github.ref_name }}
  ## Name of folder containing openjml code within OpenJML repo. Ought to match the triggering branch in 'on push'.
  FOLDER: OpenJML21

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ## Just use one instance of each kind of OS
        os: [ ubuntu-22.04, macos-14 ]
      fail-fast: false

    steps:
    - name: OS setup
        uses: ./.github/actions/os-setup/
    - name: Checkout OpenJML
      run: |
        echo branch ${{ github.ref_name }} $BRANCH "::" ${BRANCH}
        git config --global core.autocrlf input
        git clone -b ${{ github.ref_name }} --depth 1 https://github.com/OpenJML/OpenJML
        git clone -b ${{ github.ref_name }} --depth 1 https://github.com/OpenJML/Specs
        git clone -b master-21 --depth 1 https://github.com/OpenJML/OpenJMLDemo
        git clone -b master --depth 1 https://github.com/OpenJML/Solvers
        git clone -b master --depth 1 https://github.com/OpenJML/JMLAnnotations
        git clone -b master --depth 1 https://github.com/OpenJML/openjml.github.io
    - name: Build OpenJML release on Windows
      if: runner.os == 'Windows'
      shell: wsl-bash {0}
      run: |
        cd /mnt/d/a/OpenJML/OpenJML
        cd OpenJML/OpenJML21
        bash ./configure
        make release release-test
    - name: Build OpenJML release on non-Windows
      if: runner.os != 'Windows'
      run: |
        cd OpenJML/$FOLDER
        bash ./configure
        make release 
    - name: Test the release
      run: |
        make -C OpenJML/$FOLDER release-test || true
    - uses: actions/upload-artifact@v4
      with:
        name: openjml-build
        path: OpenJML

    - name: Run userguide tests
      run: |
        PATH=../../../../$FOLDER:$PATH make -C OpenJML/OpenJMLTest userguide-tests-released || true

    - name: Run tutorial tests
      run: |
        PATH=../../OpenJML/$FOLDER:$PATH make -C OpenJML/OpenJMLTest tutorial-tests-git || true

    - name: Run json tests
      run: |
        PATH=../../../$FOLDER:$PATH make -C OpenJML/OpenJMLTest json-tests || true

    - name: Run unit tests
      run: |
        ##make -C OpenJML/OpenJMLTest unittests-par
        ##the following would run all the above test steps in one step
        ##make -C OpenJML/OpenJMLTest openjml-test-git

  json-test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ## Just use one instance of each kind of OS
        os: [ ubuntu-22.04, macos-14 ]
      fail-fast: false

    steps:
    - name: OS setup
        uses: ./.github/actions/os-setup/

    - uses: actions/download-artifact@v4
      with:
        name: openjml-build
        path: OpenJML
    - name: check
      run: |
        pwd
        ls
    - name: Run json tests
      run: |
        PATH=../../../$FOLDER:$PATH make -C OpenJML/OpenJMLTest json-tests || true

