name: Nightly test of OpenJML

## This workflow runs all the unit and functionality tests on a build of the current developmenet environment for OpenJML
## that is, on the HEAD of branch dev-21 as it has been pushed to the github repo.
## The workflow is divided into jobs: the main job builds OpenJLM on each tested OS; then there are four jobs that do the actual testing.
## This separation allows the testing to be done in parallel across all 4 kinds of tets and all the OSes; if the 4 kinds of tests were executed sequentially
## a failure of one would prevent testing the rest.
## The drawback of this organization is that a failure to build one of the OSes prevents testing all of the tests for all OSes, because of how github 
## workflow job dependencies work.

on:
  workflow_dispatch:
  push:
    branches: [ dev-21 ]
#  schedule:
#    - cron: "0 0 * * *"

env:
  ## Branch to build from (both in OpenJML and Specs). (JMLAnnotation, Solvers, openjml.github.io are fixed to be 'master')
  ## The github branch that was pushed
  BRANCH: ${{ github.ref_name }}
  ## Name of folder containing openjml code within OpenJML repo. Ought to match the triggering branch in 'on push'.
  FOLDER: OpenJML21

jobs:

  ## This job defines a shared value for the matrix of OS runners to be used everywhere
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix-config: ${{ steps.set-matrix.outputs.matrix }} # Define output
    steps:
      - id: set-matrix
        run: |
          ## Edit the list here to add or remove OSes from being tested by this workflow
          echo 'matrix=[ "macos-14", "ubuntu-22.04", "ubuntu-latest" ]' >> "$GITHUB_OUTPUT"

  ## This job builds a development version of OpenJML as part of a trial release build
  ## and then uploads the built environment as a github artifact
  build:
    needs: prepare-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:  ${{ fromJson(needs.prepare-matrix.outputs.matrix-config) }}
      fail-fast: false

    steps:
    - name: OS setup
      uses: ./.github/actions/os-setup/
    - name: init
      run: |
        echo Initial state
        pwd
        ls
    - name: Checkout actions
      uses: actions/checkout@v6
    - name: after initialization
      run: |
        echo post-checkout state
        pwd
        ls
    - name: Checkout OpenJML
      uses: ./.github/actions/openjml-checkout/
      with:
        branch: ${{ github.ref_name }}
    - name: Build OpenJML
      uses: ./.github/actions/openjml-build/
      with:
        test: false
    - name: Test the release
      run: |
        pwd
        ls ..
        echo PP
        ls ../..
        make -C OpenJML/$FOLDER release-test || true
    - uses: pyTooling/upload-artifact@v6
      with:
        name: openjml-build-${{ matrix.os }}
        path: .
        overwrite: true
        include-hidden-files: true

  ## This job downloads the built environment and runs the unit tests 
  unit-test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:  ${{ fromJson(needs.prepare-matrix.outputs.matrix-config) }}
      fail-fast: false

    steps:
    - name: Checkout actions 
      uses: actions/checkout@v4
    - name: OS setup
      uses: ./.github/actions/os-setup/
    - name: Download
      uses: pyTooling/download-artifact@v6
      with:
        name: openjml-build-${{ matrix.os }}
        path: OpenJML
    - name: Run unit tests
      run: |
        PATH=../../$FOLDER:$PATH make -C OpenJML/OpenJMLTest unittests-par
        ##the following would run all the above test steps in one step
        ##make -C OpenJML/OpenJMLTest openjml-test-git

  ## This job downloads the built environment and runs the tutorial tests
  tutorial-test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:  ${{ fromJson(needs.prepare-matrix.outputs.matrix-config) }}
      fail-fast: false

    steps:
    - name: Checkout actions 
      uses: actions/checkout@v4
    - name: OS setup
      uses: ./.github/actions/os-setup/
    - name: Upload
      uses: pyTooling/download-artifact@v6
      with:
        name: openjml-build-${{ matrix.os }}
        path: OpenJML
    - name: Run tutorial tests
      run: |
        PATH=../../OpenJML/$FOLDER:$PATH make -C OpenJML/OpenJMLTest tutorial-tests-git

  ## This job downloads the built environment and then runs the json tests
  json-test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:  ${{ fromJson(needs.prepare-matrix.outputs.matrix-config) }}
      fail-fast: false

    steps:
    - name: Checkout actions 
      uses: actions/checkout@v4
    - name: OS setup
      uses: ./.github/actions/os-setup/
    - name: Upload
      uses: pyTooling/download-artifact@v6
      with:
        name: openjml-build-${{ matrix.os }}
        path: OpenJML
    - name: data
      run: |
        ls
        pwd
        ls ..
    - name: Run json tests
      run: |
        PATH=../../../$FOLDER:$PATH make -C OpenJML/OpenJMLTest json-tests

  ## This job downloads the build environment and then runs the userguide tests
  ## (which involves cloning the userguide and its examples from OverLeaf)
  userguide-test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:  ${{ fromJson(needs.prepare-matrix.outputs.matrix-config) }}
      fail-fast: false

    steps:
    - name: Checkout actions 
      uses: actions/checkout@v4
    - name: OS setup
      uses: ./.github/actions/os-setup/
    - name: Upload
      uses: pyTooling/download-artifact@v6
      with:
        name: openjml-build-${{ matrix.os }}
        path: OpenJML
    - name: Run userguide tests
      run: |
        PATH=../../../../$FOLDER:$PATH make -C OpenJML/OpenJMLTest userguide-tests-released

